.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number_2__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number_2__c</fullName>
    <label>AHPRA Number #2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number_3__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number_3__c</fullName>
    <label>AHPRA Number #3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number__c</fullName>
    <label>AHPRA Candidate Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Add_to_Ahpra_nightly_Batch_Job__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Ahpra_nightly_Batch_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to Ahpra nightly Batch Job</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Ahpra_Last_Checked__c.field-meta.xml
<CustomField>
    <fullName>Ahpra_Last_Checked__c</fullName>
    <label>Ahpra Last Checked</label>
    <type>Date</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Allow_Auto_Fetch_of_Ahpra_Details__c.field-meta.xml
<CustomField>
    <fullName>Allow_Auto_Fetch_of_Ahpra_Details__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if this record is allowed to be added to the Ahpra Batch Job.  This is set automatically after the initial manual Ahpra check is made.  If the fetch is successful, this will be auto populated.

If any Ahpra number is added or edited, this will be set to false until another manual check is made.</description>
    <inlineHelpText>Determines if this record is allowed to be added to the Ahpra Batch Job.  This is set automatically after the initial manual Ahpra check is made.  If the fetch is successful, this will be auto populated.

If any Ahpra number is added or edited, this will be set to false until another manual check is made.</inlineHelpText>
    <label>Allow Auto Fetch of Ahpra Details</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/SIM_AhpraCandidateCheckBatch.cls
global class SIM_AhpraCandidateCheckBatch implements Database.Batchable<SObject>, Database.stateful, Database.AllowsCallouts {

    // Member variable to store the list across batches
    // private 

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, aa_AHPRA_Number__c, aa_AHPRA_Number_2__c,
                   aa_AHPRA_Number_3__c, Allow_Auto_Fetch_of_Ahpra_Details__c, 
                   Add_to_Ahpra_nightly_Batch_Job__c, Ahpra_Last_Checked__c
            FROM Contact
            WHERE Allow_Auto_Fetch_of_Ahpra_Details__c = true 
              AND Add_to_Ahpra_nightly_Batch_Job__c = true
              AND Ahpra_Last_Checked__c != TODAY
              AND (aa_AHPRA_Number__c != null OR aa_AHPRA_Number_2__c != null OR aa_AHPRA_Number_3__c != null)
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<String> ahpraCodeList = new List<String>();
        List<List<String>> ahpraNumberList = new List<List<String>>();
        List<Contact> processedRecords = new List<Contact>();

        for(Contact c : scope) {
            if(c.aa_AHPRA_Number__c != null) ahpraCodeList.add(c.aa_AHPRA_Number__c);
            if(c.aa_AHPRA_Number_2__c != null) ahpraCodeList.add(c.aa_AHPRA_Number_2__c);
            if(c.aa_AHPRA_Number_3__c != null) ahpraCodeList.add(c.aa_AHPRA_Number_3__c);
        }

        if(!ahpraCodeList.isEmpty()) {
            ahpraNumberList.add(ahpraCodeList);
            List<SIM_AhpraIntegrationHandler.ahpraResponse> res = SIM_AhpraIntegrationHandler.sendRequest(ahpraNumberList);

            // Add successfully processed contacts
            processedRecords.addAll(scope);
        }

        // System.debug('Processed Records: ' + processedRecords.size());
        for(Contact c : processedRecords) {
            // System.debug('Updating Contact Id: ' + c.Id + ' Previous Ahpra_Last_Checked__c: ' + c.Ahpra_Last_Checked__c);
            c.Ahpra_Last_Checked__c = Date.today();
        }
        
        Database.SaveResult[] results = Database.update(processedRecords, false);
        for (Integer i = 0; i < results.size(); i++) {
            if(!results[i].isSuccess()) {
                System.debug('❌ Failed to update Contact Id: ' + processedRecords[i].Id + ' Error: ' + results[i].getErrors()[0].getMessage());
            } else {
                System.debug('✅ Updated Contact Id: ' + processedRecords[i].Id + ' New Ahpra_Last_Checked__c: ' + processedRecords[i].Ahpra_Last_Checked__c);
            }
        }        
    }

    global void finish(Database.BatchableContext BC) {
    }

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new SIM_AhpraCandidateCheckBatch(), 10);
    }
}