.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Auto_Broadcast__c.field-meta.xml
<CustomField>
    <fullName>Auto_Broadcast__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Broadcast</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ShiftAutoBroadcastHandler.cls
public class ShiftAutoBroadcastHandler {

    private static Boolean isRunning = false;

    public static void runAutoBroadcast(List<sirenum__Shift__c> shifts, Map<Id, sirenum__Shift__c> oldShiftMap ) {
        if (isRunning) return;
        isRunning = true;

        List<sirenum__Shift__c> autoBroadcastShifts = new List<sirenum__Shift__c>();

        for (sirenum__Shift__c shift : shifts) {

            if (oldShiftMap == null) {
                if (shift.Auto_Broadcast__c == true) {
                    autoBroadcastShifts.add(shift);
                }
            }
            else {
                sirenum__Shift__c oldShift = oldShiftMap.get(shift.Id);

                if (shift.Auto_Broadcast__c == true &&
                    oldShift.Auto_Broadcast__c == false) {

                    autoBroadcastShifts.add(shift);
                }
            }
        }

        if (!autoBroadcastShifts.isEmpty()) {
            ShiftBiddingService.autoBidShiftDemands(autoBroadcastShifts);
        }

        isRunning = false;
    }
}