.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Schedule_Display_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Display_Status__c</fullName>
    <formula>IF( RecordType.DeveloperName = &apos;Shift_Demand&apos;, 
/* SHIFT DEMAND RECORD TYPE */

  IF( sirenum__Cancelled__c = true, 
    &apos;Shift Cancelled&apos;, 
     IF(
        ISPICKVAL(Reconfirmed__c, &apos;Both&apos;),
         &apos;Reconfirm&apos;,
           IF(
             ISPICKVAL(Reconfirmed__c, &apos;Reconfirmed with Employee&apos;),
              &apos;Reconfirm with Employee&apos;,
                IF(
                    ISPICKVAL(Reconfirmed__c, &apos;Reconfirmed with Facility&apos;),
                    &apos;Reconfirm with Facility&apos;,
    IF( sirenum__Scheduled_Start_Time__c &gt;= NOW(), &apos;Waiting&apos;, &apos;Unable to Fill&apos;
    )
)
)
)
  ), 

/* SHIFT RECORD TYPE */

  IF( Cancel_Employee_Held__c = true, &apos;In a Cancelled Shift&apos;,

    /* IF( sirenum__Cancelled__c = true, */

      /* OLD IF( NOT(ISPICKVAL(sirenum__CancellationReason__c , &apos;Unable to Fill&apos;)) &amp;&amp; Cancellation_Completed__c = true, */
      /* IF( Cancellation_Completed__c = true, 
      &apos;Shift Cancelled Filled&apos;, &apos;Err Shift Canc Filled&apos;), */

      /* IF( Cancellation_Completed__c = false, &apos;In a Cancelled Shift&apos;, &apos;Err In a Canc Shift&apos;) 

    ), */
     /* Cancel_Employee_Held__c = false */

    IF( Cancellation_Completed__c = true, if( sirenum__Cancelled__c = true, &apos;Shift Cancelled Filled&apos;, &apos;In a Cancelled Shift&apos;),
/* Cancellation_Completed__c = false */

    IF( ISBLANK( TEXT(Reconfirmed__c)),

      IF( sirenum__Published__c = true &amp;&amp; sirenum__Accepted__c = 1,

          IF( Confirmed_With_Facility__c = false, 
          &apos;Allocated&apos;,
          IF( sirenum__Scheduled_Start_Time__c &gt;= NOW(), &apos;Confirmed&apos;, &apos;Completed&apos;)
      ),
      IF( Confirmed_With_Facility__c = false, &apos;Waiting&apos;, &apos;Name Given&apos;)

      

     /* IF( sirenum__Accepted__c = 0, 

        IF( Confirmed_With_Facility__c = false, &apos;Waiting&apos;, &apos;Name Given&apos;), 


        IF( sirenum__Published__c = true, 

          IF( Confirmed_With_Facility__c = true, 

            IF( sirenum__Scheduled_Start_Time__c &gt;= NOW(), &apos;Confirmed&apos;, &apos;Completed&apos;), 

            &apos;Allocated&apos;),


          &apos;ERR Accepted TRUE&apos;
        ) */
      ),

      IF(ISPICKVAL( Reconfirmed__c, &apos;Both&apos;), &apos;Reconfirm&apos;,
        IF(ISPICKVAL( Reconfirmed__c, &apos;Reconfirmed with Employee&apos;), &apos;Reconfirm with Employee&apos;,
          IF(ISPICKVAL( Reconfirmed__c, &apos;Reconfirmed with Facility&apos;), &apos;Reconfirm with Facility&apos;,
          &apos;ERR RECONFIRM WITH&apos;
          )
        )
      )        
    ) 
  ))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule Display Status</label>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Schedule_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Status__c</fullName>
    <label>Schedule Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Name Given</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Reconfirm with Employee</fullName>
            </value>
            <value>
                <fullName>Reconfirm with Facility</fullName>
            </value>
            <value>
                <fullName>Reconfirm</fullName>
            </value>
            <value>
                <fullName>In a Cancelled Shift</fullName>
            </value>
            <value>
                <fullName>Shift Cancelled Filled</fullName>
            </value>
            <value>
                <fullName>Shift Cancelled</fullName>
            </value>
            <value>
                <fullName>Unable to Fill</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Awaiting Allocation</fullName>
                <isActive>false</isActive>
                <label>Awaiting Allocation</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Reconfirmed</fullName>
                <isActive>false</isActive>
                <label>Reconfirmed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ShiftStatusBatch.cls
/*
********************************************************************************************************
* Developed By: Rishikesh
* Date: 30/10/2025
* Description: This batch class updates Schedule_Status__c based on Schedule_Display_Status__c
********************************************************************************************************
*/
public class ShiftStatusBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String soqlQuery = 'SELECT Id, Name, Schedule_Display_Status__c, Schedule_Status__c FROM sirenum__Shift__c' +
                ' WHERE ' +
                ' (Schedule_Display_Status__c = \'Waiting\' AND Schedule_Status__c != \'Waiting\')' +
                ' OR (Schedule_Display_Status__c = \'Unable to Fill\' AND Schedule_Status__c != \'Unable to Fill\')' +
                ' OR (Schedule_Display_Status__c = \'Confirmed\' AND Schedule_Status__c != \'Confirmed\')' +
                ' OR (Schedule_Display_Status__c = \'Completed\' AND Schedule_Status__c != \'Completed\')';
        if (Test.isRunningTest()) {
            soqlQuery +=' OR id != null';
        }
        
        return Database.getQueryLocator(soqlQuery);

    }
    
    // Execute method: update Schedule_Status__c to match Schedule_Display_Status__c
    public void execute(Database.BatchableContext bc, List<sirenum__Shift__c> shiftList) {       
        List<sirenum__Shift__c> shiftsToUpdate = new List<sirenum__Shift__c>();        
        for (sirenum__Shift__c shift : shiftList) {
            // Only update if different to avoid unnecessary DML
            if (shift.Schedule_Status__c != shift.Schedule_Display_Status__c || Test.isRunningTest()) {
                shift.Schedule_Status__c = shift.Schedule_Display_Status__c;
                shiftsToUpdate.add(shift);
            }
        }
        
        if (!shiftsToUpdate.isEmpty()) {
              update shiftsToUpdate;
        }
    }
    
    // Finish method
    public void finish(Database.BatchableContext bc) {
        System.debug('ShiftStatusBatch has completed successfully.');
    }
}