.vscode/allianceuat_compare/force-app/main/default/objects/VMS_Shift_Error__c/VMS_Shift_Error__c.object-meta.xml
<CustomObject>
    <description>Contain Shift Errors when creating/updating from VMS/ShiftMatch</description>
    <label>VMS Shift Error</label>
    <nameField>
        <displayFormat>VMS-ERR-{0000000}</displayFormat>
        <label>VMS Shift Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VMS Shift Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/VMS_Shift_Error__c/fields/External_Shift_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Shift_ID__c</fullName>
    <description>Shift ID from VMS</description>
    <externalId>true</externalId>
    <label>External Shift ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/VMS_Shift_Error__c/fields/VMS_Shift_Info__c.field-meta.xml
<CustomField>
    <fullName>VMS_Shift_Info__c</fullName>
    <label>VMS Shift Info</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/VMS_Shift_Error__c/fields/VMS_Shift_URL__c.field-meta.xml
<CustomField>
    <fullName>VMS_Shift_URL__c</fullName>
    <label>VMS Shift URL</label>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/AttachEmailToObjectTest.cls
@isTest
private class AttachEmailToObjectTest {

@isTest
    static void testAttachEmailLead() {

        VMS_Shift_Error__c shiftError = new VMS_Shift_Error__c(
            VMS_Source__c = 'Emprevo',
            External_Shift_ID__c = 'TestShift1234', 
            VMS_Shift_URL__c = 'www.emprevotest.com',
            VMS_Shift_Info__c = 'Shift Info'//,
            // Error_Type__c = request.errorType,
            // Error_Message__c = request.errorMessage,
        );
        insert shiftError;
        
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        email.toAddresses = new String[] {'1218_Test@testemail.1218global.com'};
        email.subject = 'Test Subject';
        email.plainTextBody = 'Test Email Body';
        email.htmlBody = 'Test Email Body';
        
        Test.startTest();
        AttachEmailToObject.attachEmail(email, shiftError.Id);
        Test.stopTest();

        List<EmailMessage> emails = [SELECT Id, RelatedToId FROM EmailMessage WHERE RelatedToId = :shiftError.Id];
        System.assertEquals(1, emails.size(), 'Number of emails should be 1');
        System.assertEquals(shiftError.Id, emails[0].RelatedToId, 'Email should be associated with Lead');
    }
}