.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/Cost_Center__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select Branch for the Cost Center</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cost Centers</relationshipLabel>
    <relationshipName>Cost_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <inlineHelpText>Enter the Public Group Name</inlineHelpText>
    <label>Public Group</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <inlineHelpText>Enter the Developer Name of the Application SMS Config Custom Metadata</inlineHelpText>
    <label>SMS Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <inlineHelpText>Select Team for Cost Center</inlineHelpText>
    <label>Team</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Team</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/Cost_Center_User__c.object-meta.xml
<CustomObject>
    <label>Cost Center User</label>
    <nameField>
        <displayFormat>CCU-{000000}</displayFormat>
        <label>Cost Center User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Center Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <referenceTo>Cost_Center__c</referenceTo>
    <relationshipLabel>Cost Center Users</relationshipLabel>
    <relationshipName>Cost_Center_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this the Primary Cost Center?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select User for Cost Center</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/User/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <description>Connect User to an SMS Cost Center</description>
    <inlineHelpText>Connect User to an SMS Cost Center</inlineHelpText>
    <label>SMS Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra Staff Adelaide Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Adelaide General</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury General</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing General</fullName>
            </value>
            <value>
                <fullName>Perth Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Perth Nursing General</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing General</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing  Allocations</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing General</fullName>
            </value>
            <value>
                <fullName>Alliance Test One</fullName>
                <isActive>false</isActive>
                <label>Alliance Test One</label>
            </value>
            <value>
                <fullName>Alliance Test Two</fullName>
                <isActive>false</isActive>
                <label>Alliance Test Two</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/globalValueSets/Team.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Allocations</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Recruitment</fullName>
    </customValue>
    <description>Teams for Notifications</description>
    <masterLabel>Team</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

.vscode/allianceuat_compare/force-app/main/default/classes/SMSEventLoggerTest.cls
@isTest
public class SMSEventLoggerTest {

    @testSetup
    static void setupData() {
        // Insert test data for Contact, CustomNotificationType, and TextIUS_Settings__c

        Contact testContact = new Contact(FirstName = 'John', LastName = 'Doe', Phone = '1234567890',email='test332255@emailtest.com');
        insert testContact;

        // Custom Notification Type for SMS Notification
        //CustomNotificationType smsNotificationType = new CustomNotificationType(DeveloperName = 'New_SMS_Received');
        // insert smsNotificationType;

        Branch__c branch = new Branch__c(City__c = 'Adelaide', Branch_Name__c = 'Adelaide Allocations', Branch_Code__c = '1');
        insert branch;

        Cost_Center__c costCenter = new Cost_Center__c(
            Name = 'Alliance Test One', 
            Branch__c = branch.Id, 
            SMS_Cost_Center__c = 'Alliance_Nurse_Allocations', 
            Team__c = 'Allocations', 
            Public_Group__c = 'Adelaide_Nursing_Allocations');
        insert costCenter;

        Cost_Center_User__c costCenterUser = new Cost_Center_User__c(Cost_Center__c = costCenter.Id, User__c = UserInfo.getUserId(), Is_Primary__c = true);
        insert costCenterUser;


        // Mock settings for TextIUS_Settings__c
  
       
        // TextIUS_Settings__c settings = SettingsProvider.getSettings();
        SMSSettings settings = SMSSettings.getInstance();
        // settings.API_Token__c ='SECURITYTOKEN';
        // settings.Sender_Phone_Number__c = '075432333';
        // settings.API_URL__c = 'APIURL';
        // settings.SMS_Event_Description_Length__c = 100;
        // settings.Greetings__c = 'Hello test';
        // settings.Default_Admin_Id__c = 'admin id';
        // settings.Default_Name__c ='ADMIN NAME';
        // insert settings;
    }

    @isTest
    static void testLogSMSEventOutbound() {
        // Retrieve test data
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Id notifiedUserId = UserInfo.getUserId();  // Use the running user's Id for test

        // Call the logSMSEvent method for an outbound SMS
        Test.startTest();
        SMSEventLogger.logSMSEvent('outbound', '1234567890', 'Test message body', testContact.Id, notifiedUserId);
        Test.stopTest();

        // Verify that an Event record was created
        Event smsEvent = [SELECT Subject, WhoId, Description FROM Event WHERE WhoId = :testContact.Id LIMIT 1];
        System.assertEquals('SMS outbound to 1234567890', smsEvent.Subject);
        System.assertEquals('Test message body', smsEvent.Description);
        System.assertEquals(testContact.Id, smsEvent.WhoId);
    }

    @isTest
    static void testLogSMSEventInbound() {
        // Retrieve test data
        Contact testContact = [SELECT Id, FirstName, LastName FROM Contact LIMIT 1];
        Id notifiedUserId = UserInfo.getUserId();  // Use the running user's Id for test

        // Call the logSMSEvent method for an inbound SMS
        Test.startTest();
        SMSEventLogger.logSMSEvent('inbound', '1234567890', 'Test message body', testContact.Id, notifiedUserId);
        Test.stopTest();

        // Verify that an Event record was created
        Event smsEvent = [SELECT Subject, WhoId, Description FROM Event WHERE WhoId = :testContact.Id LIMIT 1];
        System.assertEquals('SMS inbound from 1234567890', smsEvent.Subject);
        System.assertEquals('Test message body', smsEvent.Description);
        System.assertEquals(testContact.Id, smsEvent.WhoId);

        // Verify that a CustomNotification was sent
        // Since we cannot query Messaging.CustomNotification, we rely on debug logs
        // Use the logs to check if the notification was sent successfully
       // String debugLog = Test.getMockHttpResponses();
        //System.assert(debugLog.contains('Notification sent'));
    }

}