.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/MobileMessaging_SMS_Message__c.object-meta.xml
<CustomObject>
    <description>This object holds the text messages sent and received. by the contact</description>
    <label>MobileMessaging SMS Message</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MobileMessaging SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MobileMessaging SMS Messages</relationshipLabel>
    <relationshipName>Text_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>inbound</fullName>
            </value>
            <value>
                <fullName>outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>SMS Message content for incoming and outgoing messages</description>
    <label>Message Content</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Message_Response__c.field-meta.xml
<CustomField>
    <fullName>Message_Response__c</fullName>
    <label>Message Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sender</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MobileMessaging_SMS_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <description>Storing the sender name at the time of sending the message in case it was changed</description>
    <label>Sender Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Short_Message__c.field-meta.xml
<CustomField>
    <fullName>Short_Message__c</fullName>
    <label>Short Message</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/MobileMessagingServiceStatusCallbackTest.cls
@isTest
private class MobileMessagingServiceStatusCallbackTest {

    @isTest static void testCaptureStatus() {
        Contact con = new Contact(LastName = 'Test', FirstName = 'Junior', MobilePhone = '+61434567890');
        insert con;
        MobileMessaging_SMS_Message__c testMessage = new MobileMessaging_SMS_Message__c();
        testMessage.Message_Response__c = 'Sent';
        testMessage.Status__c = 'Sent';
        testMessage.Source__c = 'Salesforce';
        testMessage.Direction__c = 'outbound';
        testMessage.Message_Content__c = 'Test Message';
        testMessage.Short_Message__c = 'Test Message';
        testMessage.Contact__c = con.id;
        // testMessage.Sender__c =  UserInfo.getUserId();
        // testMessage.Sender_Name__c = 'Test Sender';

        insert testMessage;

        SMSSettings settings = SMSSettings.getInstance();

        // Set up mock RestRequest and RestResponse
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/MobileMessagingServiceStatusCallback';  // Set the endpoint URL here
        req.httpMethod = 'POST';
        req.addHeader('x-messagemedia-auth', settings.inboundToken);
        // req.addParameter('messageId', testMessage.Id);
        // req.addParameter('SmsStatus', 'Delivered');

        String jsonPayload='{"metadata_sf_id": "';
        jsonPayload+= testMessage.Id;
        jsonPayload+= '", "status": "Delivered"}';
        
        req.requestBody = Blob.valueof(jsonPayload); 

        RestContext.request = req;
        RestContext.response = res;

        // Act - Call the method to test
        Test.startTest();
        String result = MobileMessagingServiceStatusCallback.captureStatus();
        Test.stopTest();

        // Assert - Verify that the record was updated correctly
        testMessage = [SELECT Message_Response__c FROM MobileMessaging_SMS_Message__c WHERE Id =: testMessage.Id];
        System.assertEquals('Delivered', testMessage.Message_Response__c);
    }
}