.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/MobileMessaging_SMS_Message__c.object-meta.xml
<CustomObject>
    <description>This object holds the text messages sent and received. by the contact</description>
    <label>MobileMessaging SMS Message</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MobileMessaging SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MobileMessaging SMS Messages</relationshipLabel>
    <relationshipName>Text_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>inbound</fullName>
            </value>
            <value>
                <fullName>outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Short_Message__c.field-meta.xml
<CustomField>
    <fullName>Short_Message__c</fullName>
    <label>Short Message</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/MobileMessagingCreatePushTopicTest.cls
@isTest
private class MobileMessagingCreatePushTopicTest {

    @isTest
    static void testMobileMessagingCreatePushTopic() {
        Test.startTest();
        MobileMessagingCreatePushTopic.createMobileMessageSMSPushTopic();
        Test.stopTest();
        
        // Verify that the PushTopic has been created with the correct properties
        PushTopic createdPushTopic = [SELECT Name, Query, ApiVersion, NotifyForOperationCreate, NotifyForOperationUpdate, 
                                              NotifyForOperationUndelete, NotifyForOperationDelete, NotifyForFields 
                                       FROM PushTopic 
                                       WHERE Name = 'MobileMessage_SMS_Watcher' 
                                       LIMIT 1];
        
        System.assertEquals('MobileMessage_SMS_Watcher', createdPushTopic.Name, 'PushTopic Name should match');
        //System.assertEquals('SELECT Id, Contact__c, Contact__r.Name, Direction__c, Short_Message__c, CreatedDate FROM MobileMessaging_SMS_Message__c', createdPushTopic.Query, 'PushTopic Query should match');
        System.assertEquals(58.0, createdPushTopic.ApiVersion, 'PushTopic ApiVersion should match');
        System.assertEquals(true, createdPushTopic.NotifyForOperationCreate, 'PushTopic NotifyForOperationCreate should be true');
        System.assertEquals(true, createdPushTopic.NotifyForOperationUpdate, 'PushTopic NotifyForOperationUpdate should be true');
        System.assertEquals(true, createdPushTopic.NotifyForOperationUndelete, 'PushTopic NotifyForOperationUndelete should be true');
        System.assertEquals(true, createdPushTopic.NotifyForOperationDelete, 'PushTopic NotifyForOperationDelete should be true');
        System.assertEquals('Referenced', createdPushTopic.NotifyForFields, 'PushTopic NotifyForFields should match');
    
 }
}