.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/MobileMessaging_SMS_Message__c.object-meta.xml
<CustomObject>
    <description>This object holds the text messages sent and received. by the contact</description>
    <label>MobileMessaging SMS Message</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MobileMessaging SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MobileMessaging SMS Messages</relationshipLabel>
    <relationshipName>Text_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>inbound</fullName>
            </value>
            <value>
                <fullName>outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>SMS Message content for incoming and outgoing messages</description>
    <label>Message Content</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Short_Message__c.field-meta.xml
<CustomField>
    <fullName>Short_Message__c</fullName>
    <label>Short Message</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/MMChatComponentControllerTest.cls
@isTest
private class MMChatComponentControllerTest {

    // Helper method to create a test contact
    private static Contact createTestContact() {
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact', 
        Email = 'example@example.com', MobilePhone = '+61481494782');
        insert testContact;
        return testContact;
    }

    // Helper method to create test SMS messages for a contact
    private static List<MobileMessaging_SMS_Message__c> createTestMessages(Contact testContact, Integer count) {
        List<MobileMessaging_SMS_Message__c> messages = new List<MobileMessaging_SMS_Message__c>();
        for (Integer i = 0; i < count; i++) {
            try {
                messages.add(new MobileMessaging_SMS_Message__c(
                    Contact__c = testContact.Id,
                    Short_Message__c = 'Test Message ' + i,
                    Direction__c   = 'Inbound',
                    Source__c      = 'SMS',
                    Status__c      = 'Received',
                    Message_Content__c = 'Test Message ' + i
                                    ));
                
            } catch (Exception e) {
                System.debug('Exception: ' + e.getMessage());
                
            }
           
        }
        insert messages;
        return messages;
    }

    @isTest static void testGetPastMessages() {
        //  create a test contact and associated messages
        Contact testContact = createTestContact();
        List<MobileMessaging_SMS_Message__c> testMessages = createTestMessages(testContact, 3);

        // Act - retrieve past messages using the controller method
        Test.startTest();
        List<MobileMessagingChatComponentController.MessageWrapper> retrievedMessages = (List<MobileMessagingChatComponentController.MessageWrapper>)MobileMessagingChatComponentController.getPastMessages(testContact.Id);
        Test.stopTest();

        // Assert - check if the correct number of messages is retrieved
        System.assertEquals(3, retrievedMessages.size(), 'There should be 3 messages retrieved for the contact.');

        // Additional assertions could be performed here to verify the content of the messages
    }

    @isTest 
    static void testGetPastMessages_fail() {
        Contact testContact = createTestContact();
        List<MobileMessaging_SMS_Message__c> testMessages = createTestMessages(testContact, 3);

        Test.startTest();
        try{
            List<MobileMessagingChatComponentController.MessageWrapper> retrievedMessages = (List<MobileMessagingChatComponentController.MessageWrapper>)MobileMessagingChatComponentController.getPastMessages(null);
        } catch (Exception e){
            System.Assert.isTrue(e != null, 'An exception should have been thrown.');
        }
        Test.stopTest();
    }

    // we would also need to write a test method for createNewMessage if it exists in our controller
    @isTest 
    static void createNewMessage_valid() {
        Contact testContact = createTestContact();
        String messageBody = 'Test Message';
        String newMessageType = 'outbound';

        Test.startTest();
        MobileMessagingChatComponentController.MessageWrapper message = MobileMessagingChatComponentController.createNewMessage(testContact.Id, messageBody, newMessageType);
        System.debug('MMChatComponentControllerTest message: ' + message);
        Test.stopTest();

        System.assertEquals('Test Message', message.messageContent, 'Message created.');
    }

    @isTest 
    static void createNewMessage_invalidNoContact() {
        Contact testContact = createTestContact();
        String messageBody = 'Test Message';
        String newMessageType = 'outbound';

        Test.startTest();
        
        try{
            MobileMessagingChatComponentController.MessageWrapper message = MobileMessagingChatComponentController.createNewMessage(null, messageBody, newMessageType);
        } catch (Exception e){
            System.Assert.isTrue(e != null, 'An exception should have been thrown.');
        }

         try{
            MobileMessagingChatComponentController.MessageWrapper message = MobileMessagingChatComponentController.createNewMessage(testContact.Id, '', newMessageType);
        } catch (Exception e){
            System.Assert.isTrue(e != null, 'An exception should have been thrown.');
        }

         try{
            MobileMessagingChatComponentController.MessageWrapper message = MobileMessagingChatComponentController.createNewMessage(testContact.Id, messageBody, '');
        } catch (Exception e){
            System.Assert.isTrue(e != null, 'An exception should have been thrown.');
        }
        Test.stopTest();

    }
}