.vscode/allianceuat_compare/force-app/main/default/objects/Alliance_General_Settings__c/Alliance_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Alliance General Settings</label>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Alliance_General_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>This field is use to keep the batch size of the Batch class &quot;ShiftStatusBatch&quot; and the Schedular class of the Batch class is &quot;ShiftStatusScheduler&quot;</description>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ShiftStatusScheduler.cls
/*
********************************************************************************************************
* Developed By: Rishikesh
* Date: 30/10/2025
* Description: This Scheduler class executes ShiftStatusBatch with Batch Size from Custom Setting using SOQL
********************************************************************************************************
*/
global class ShiftStatusScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        Alliance_General_Settings__c settings = Alliance_General_Settings__c.getInstance();

        Integer batchSize = (settings.Batch_Size__c != null) ? settings.Batch_Size__c.intValue() : 200; // directly use Number field
        
        // Execute Batch with dynamic batch size
        ShiftStatusBatch batchJob = new ShiftStatusBatch();
        Database.executeBatch(batchJob, batchSize);
    }
}