.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Certificate__c/fields/Certificate_Status__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Status__c</fullName>
    <label>Certificate Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Lapsed / Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Certificate__c/fields/Certificate_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Type_Name__c</fullName>
    <formula>b3o__Certificate_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Certificate Type Name</label>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Phone_Number__c</fullName>
    <label>Branch Phone Number</label>
    <type>Phone</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch_Email__c/Branch_Email__c.object-meta.xml
<CustomObject>
    <label>Branch Email</label>
    <nameField>
        <label>Branch Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch_Email__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branch Emails</relationshipLabel>
    <relationshipName>Branch_Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number_2__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number_2__c</fullName>
    <label>AHPRA Number #2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number_3__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number_3__c</fullName>
    <label>AHPRA Number #3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/aa_AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>aa_AHPRA_Number__c</fullName>
    <label>AHPRA Candidate Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <inlineHelpText>AHPRA number, otherwise leave blank if not relevant</inlineHelpText>
    <label>AHPRA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fixed Assets</relationshipLabel>
    <relationshipName>Fixed_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Fixed Assets</relationshipLabel>
    <relationshipName>Fixed_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch_Email__c.field-meta.xml
<CustomField>
    <fullName>Branch_Email__c</fullName>
    <inlineHelpText>Email address of branch for back of ID badge</inlineHelpText>
    <label>Branch Email</label>
    <type>Email</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Phone_Number__c</fullName>
    <inlineHelpText>To appear on back of ID badge</inlineHelpText>
    <label>Branch Phone Number</label>
    <type>Phone</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <inlineHelpText>Select which brand for appropriate logo for ID badge</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nursing</fullName>
            </value>
            <value>
                <fullName>Extra Staff</fullName>
            </value>
            <value>
                <fullName>R&amp;R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>Position title to appear on the front of the ID badge</inlineHelpText>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <inlineHelpText>Preferred name to appear on the front of the badge</inlineHelpText>
    <label>Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/PDF_IDBadgeExtension.cls
public with sharing class PDF_IDBadgeExtension {
    public TR1__Fixed_Assets__c record {get;set;}
    // public List<TR1__EmploymentHistory__c> empHists {get;set;}
    public List<b3o__Document_Submission__c> docSubmissions {get;set;}
    public List<b3o__Certificate__c> certs {get;set;}
    public List<ContentDocumentLink> docLinks {get;set;}

    public PDF_IDBadgeExtension(ApexPages.StandardController stdController) {
        System.debug(LOGGINGLEVEL.ERROR, stdController.getId());

        // this.record = [SELECT Id, 
        //     Name, 
        //     FirstName, 
        //     LastName, 
        //     aa_AHPRA_Number__c,
        //     aa_AHPRA_Number_2__c,
        //     aa_AHPRA_Number_3__c,
        //     MailingStreet, 
        //     MailingCity
        //     // More Fields Here 
        //     FROM Contact 
        //     WHERE Id = :stdController.getId()];

        this.record = [SELECT Id, 
            Preferred_Name__c,       
            Position__c, 
            AHPRA_Number__c,
            Assigned__c,
            Assigned__r.Name,
            Assigned__r.sirenum__Photo_ID__c,
            Assigned__r.PhotoURL,
            Branch__r.Branch_Name__c,
            Branch_Email__c,
            // // Branch__r.Branch_Phone_Number__c,
            Branch_Phone_Number__c,
            // // Branch__r.Branch_Phone_Number__c,
            Brand__c
            // // More Fields Here 
            FROM TR1__Fixed_Assets__c 
            WHERE Id = :stdController.getId()];

        // List<b3o__Document_Submission__c> docSubmissions  = [SELECT Id, 
        //     b3o__Contact__c, 
        //     b3o__Document__r.Name, 
        //     b3o__Form_Response__c, 
        //     b3o__Status__c,
        //     CreatedDate
        //     FROM b3o__Document_Submission__c 
        //     WHERE b3o__Contact__c = :this.record.Assigned__c
        //     AND b3o__Document__r.Name = 'Photo ID Form' 
        //     AND b3o__Status__c in ('Pending Review', 'Approved')
        //     ORDER BY CreatedDate DESC
        //     LIMIT 1];

        // this.docSubmissions = docSubmissions;

        List<b3o__Certificate__c> certs = [SELECT Id, 
            b3o__Contact__c, 
            Certificate_Type_Name__c, 
            Certificate_Status__c,
            b3o__Status__c,
            CreatedDate
            FROM b3o__Certificate__c 
            WHERE b3o__Contact__c = :this.record.Assigned__c
            AND Certificate_Type_Name__c = 'Photo ID'
            AND Certificate_Status__c in ('Pending Review',  'Complete', 'Final Review') 
            ORDER BY CreatedDate DESC
            LIMIT 1];

        this.certs = certs;

        // if (docSubmissions.size() > 0) {
        if (certs.size() > 0) {
            List<ContentDocumentLink> docLinks = [SELECT Id, 
                ContentDocumentId, 
                LinkedEntityId, 
                ContentDocument.FileType,
                ContentDocument.LatestPublishedVersionId
                FROM ContentDocumentLink 
                WHERE LinkedEntityId= :this.certs[0].Id 
                AND ContentDocument.FileType in ('JPG','PNG')];

            this.docLinks = docLinks;
        } else {
            this.docLinks = null;
        }
 
    }

    public String photoIdLink {
        get {
            // System.debug(LOGGINGLEVEL.ERROR, 'this.record.Assigned__r?.sirenum__Photo_ID__c: ' + this.record.Assigned__r?.sirenum__Photo_ID__c);
            // System.debug(LOGGINGLEVEL.ERROR, 'this.record.Assigned__r?.sirenum__Photo_ID__c: ' + this.record.Assigned__r?.PhotoURL);    
            // return '/servlet/servlet.FileDownload?file=' + this.record.Assigned__r?.sirenum__Photo_ID__c;
             // return '/servlet/servlet.FileDownload?file=0699t0000059GYvAAM';
            // return '/sfc/servlet.shepherd/version/download/0699t0000059GYvAAM';
            // return '/sfc/servlet.shepherd/version/download/0689t000005pQC5AAM';
            // return '/servlet/servlet.FileDownload?file=0689t000005pQC5AAM';
            // if (this.docLinks.size() > 0){

            if (this.docLinks.size() > 0){
            // if (this.docLinks != null){
                System.debug(LOGGINGLEVEL.ERROR, 'this?.docLinks.size(): ' + this?.docLinks.size());
                System.debug(LOGGINGLEVEL.ERROR, 'this?.docLinks: ' + this?.docLinks);
                // return '/servlet/servlet.FileDownload?file=' + this?.docLinks[0].ContentDocumentId;
                System.debug(LOGGINGLEVEL.ERROR, 'this?.docLinks[0].ContentDocument.LatestPublishedVersionId: ' + this?.docLinks[0].ContentDocument.LatestPublishedVersionId);
                return '/sfc/servlet.shepherd/version/download/' + this?.docLinks[0].ContentDocument.LatestPublishedVersionId;
            
            } else {
                return '';
            }
                     
        }
    }

    // public String ahpraNumbers {
    //     get {
    //         List<String> listARPHANumbers = new List<String>();
    //         String result = '';
    //         if (this.record.aa_AHPRA_Number__c != null) {
    //             listARPHANumbers.add(this.record?.aa_AHPRA_Number__c);
    //         }
    //         if (this.record.aa_AHPRA_Number__c != null) {
    //             listARPHANumbers.add(this.record?.aa_AHPRA_Number_2__c);
    //         }
    //         if (this.record.aa_AHPRA_Number__c != null) {
    //             listARPHANumbers.add(this.record?.aa_AHPRA_Number_3__c);
    //         }

    //         return listARPHANumbers.toString();
    //     }
    // }
}