.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Australia_Timezones</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session_Invitation__c/fields/Booked_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Booked_Timestamp__c</fullName>
    <label>Booked Timestamp</label>
    <type>DateTime</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session_Invitation__c/fields/Booking_End_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Booking_End_Time_Local__c</fullName>
    <label>Booking End Time (Local)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session_Invitation__c/fields/Booking_End_Time_Session__c.field-meta.xml
<CustomField>
    <fullName>Booking_End_Time_Session__c</fullName>
    <label>Booking End Time (Session)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session_Invitation__c/fields/Booking_Start_Time_Session__c.field-meta.xml
<CustomField>
    <fullName>Booking_Start_Time_Session__c</fullName>
    <label>Booking Start Time (Session)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Session_Invitation__c/fields/Booking_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>Booking_Time_Local__c</fullName>
    <label>Booking Start Time (Local)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Candidate_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Timezone__c</fullName>
    <label>Candidate Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Australia_Timezones</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/globalValueSets/Australia_Timezones.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australia/Adelaide</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Brisbane</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Broken_Hill</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Currie</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Darwin</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Eucla</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Hobart</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Lindeman</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Lord_Howe</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Melbourne</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Perth</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Edmonton</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Halifax Regional Municipality</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Newfoundland</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Regina</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>Canada/Winnipeg</fullName>
    </customValue>
    <customValue>
        <fullName>Indian/Christmas</fullName>
    </customValue>
    <customValue>
        <fullName>Indian/Cocos</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland/Dublin</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand/Tokelau</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand/Waitangi</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand/Wellington</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific/Norfolk</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom/London</fullName>
    </customValue>
    <customValue>
        <fullName>United States/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>United States/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>United States/Honolulu</fullName>
    </customValue>
    <customValue>
        <fullName>United States/Houston</fullName>
    </customValue>
    <masterLabel>Australia Timezones</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

.vscode/allianceuat_compare/force-app/main/default/classes/SessionInvitationTriggerHandler.cls
public without sharing class SessionInvitationTriggerHandler {
    static final String DEFAULT_TIMEZONE = 'Australia/Sydney';
    public static void handleChange() {
        List<b3o__Session_Invitation__c> invitations = (List<b3o__Session_Invitation__c>) Trigger.new;
        Map<id, b3o__Session_Invitation__c> oldMap = (Map<id, b3o__Session_Invitation__c>) Trigger.oldMap;
                 
        List<b3o__Session_Invitation__c> toProcess = new List<b3o__Session_Invitation__c>();
        Set<id> contactIds = new Set<id>();
        Set<id> sessionIds = new Set<id>();
        for (b3o__Session_Invitation__c i : invitations) {
            if (i.b3o__Booking_Start_Time__c != null && i.b3o__Booking_End_Time__c != null &&
               (oldMap == null || oldMap.get(i.id) == null 
               || oldMap.get(i.id).b3o__Booking_Start_Time__c != i.b3o__Booking_Start_Time__c || i.Booking_Time_Local__c == null || i.Booking_End_Time_Local__c == null
               || i.Booking_Start_Time_Session__c == null || i.Booking_End_Time_Session__c == null)) {
               toProcess.add(i);                                    
               contactIds.add(i.b3o__Contact__c);
               sessionIds.add(i.b3o__Session__c);
            }
        }

        if (toProcess.isEmpty()) {
            return;
        }

        Map<id, Contact> contacts = new Map<id, Contact>([select id, Candidate_Timezone__c from Contact where id = :contactIds]);
        Map<id, b3o__Session__c> sessions = new Map<id, b3o__Session__c>([select id, Timezone__c from b3o__Session__c where id = :sessionIds]);
                
        for (b3o__Session_Invitation__c i : toProcess) {
            String timezone = (contacts.get(i.b3o__Contact__c).Candidate_Timezone__c == null) ? 
                              sessions.get(i.b3o__Session__c).Timezone__c : contacts.get(i.b3o__Contact__c).Candidate_Timezone__c;
            timezone = (timezone == null) ? DEFAULT_TIMEZONE : timezone;
            String sessionTimezone = (sessions.get(i.b3o__Session__c).Timezone__c == null) ? DEFAULT_TIMEZONE : sessions.get(i.b3o__Session__c).Timezone__c;

            i.Booking_Time_Local__c = i.b3o__Booking_Start_Time__c.format('dd/MM/yyyy h:mm a', timezone);
            i.Booking_End_Time_Local__c = i.b3o__Booking_End_Time__c.format('dd/MM/yyyy h:mm a', timezone);
            i.Booking_Start_Time_Session__c = i.b3o__Booking_Start_Time__c.format('dd/MM/yyyy h:mm a', sessionTimezone);
            i.Booking_End_Time_Session__c = i.b3o__Booking_End_Time__c.format('dd/MM/yyyy h:mm a', sessionTimezone);
            i.Booked_Timestamp__c = System.now();
        }
    }        
}