.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/Application_SMS_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>X1218 Application SMS Configuration</label>
    <pluralLabel>Application SMS Configurations</pluralLabel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Account_SID__c</fullName>
    <label>Account SID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The api end point</description>
    <label>API Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Site_Domain_URL__c.field-meta.xml
<CustomField>
    <fullName>API_Site_Domain_URL__c</fullName>
    <label>API Site Domain URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Authentication_Token__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Token__c</fullName>
    <description>this is either the authentication token Auth Token or the API Token depending on the SMS provider</description>
    <label>Authentication Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Admin_Id__c</fullName>
    <label>Default Admin Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Admin_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Admin_Name__c</fullName>
    <label>Default Admin Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Greetings_Message__c.field-meta.xml
<CustomField>
    <fullName>Default_Greetings_Message__c</fullName>
    <label>Default Greeting Message</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Inbound_Header__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Header__c</fullName>
    <label>Inbound Header</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Inbound_Token__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Token__c</fullName>
    <description>Token to confirm SMS and Delivery Reports are coming from SMS Provider</description>
    <label>Inbound Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Twilio</fullName>
            </value>
            <value>
                <fullName>TextUs</fullName>
            </value>
            <value>
                <fullName>MessageMedia</fullName>
                <default>true</default>
                <label>MessageMedia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Sender_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Phone_Number__c</fullName>
    <label>Sender Phone Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <label>SMS Cost Center</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/User/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <description>Connect User to an SMS Cost Center</description>
    <inlineHelpText>Connect User to an SMS Cost Center</inlineHelpText>
    <label>SMS Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra Staff Adelaide Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Adelaide General</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury General</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing General</fullName>
            </value>
            <value>
                <fullName>Perth Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Perth Nursing General</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing General</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing  Allocations</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing General</fullName>
            </value>
            <value>
                <fullName>Alliance Test One</fullName>
                <isActive>false</isActive>
                <label>Alliance Test One</label>
            </value>
            <value>
                <fullName>Alliance Test Two</fullName>
                <isActive>false</isActive>
                <label>Alliance Test Two</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/SettingsProvider.cls
public class SettingsProvider {
    @AuraEnabled(cacheable=true)
    // public static TextIUS_Settings__c getSettings() {
    //     return TextIUS_Settings__c.getInstance();
    // }

    public static Application_SMS_Configuration__mdt getSettings(String costCenter) {
        if (!Schema.sObjectType.Application_SMS_Configuration__mdt.isAccessible()) {
            throw new InsufficientAccessRightsException('User does not have read access to Application_SMS_Configuration__mdt');
        }
        System.debug('SettingsProvider costCenter: ' + costCenter);
        try {
            return [SELECT Account_SID__c, API_Endpoint__c, API_Site_Domain_URL__c, Authentication_Token__c, 
                           Default_Admin_Id__c, Default_Admin_Name__c, isActive__c, Provider_Name__c,
                           Sender_Phone_Number__c, Default_Greetings_Message__c, SMS_Cost_Center__c, 
                           Inbound_Header__c, Inbound_Token__c
                    FROM Application_SMS_Configuration__mdt
                    // WHERE SMS_Cost_Center__c = :costCenter
                    WHERE DeveloperName = :costCenter
                    LIMIT 1];
        } catch (Exception e) {
            System.debug('Exception thrown: ' + e.getMessage());
            throw new CustomSettingException('Error fetching SMS settings');
        }
    }

    public class InsufficientAccessRightsException extends Exception {}
    public class CustomSettingException extends Exception {}
}