.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/Application_SMS_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>X1218 Application SMS Configuration</label>
    <pluralLabel>Application SMS Configurations</pluralLabel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <label>SMS Cost Center</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/Cost_Center__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select Branch for the Cost Center</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cost Centers</relationshipLabel>
    <relationshipName>Cost_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <inlineHelpText>Enter the Public Group Name</inlineHelpText>
    <label>Public Group</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <inlineHelpText>Enter the Developer Name of the Application SMS Config Custom Metadata</inlineHelpText>
    <label>SMS Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <inlineHelpText>Select Team for Cost Center</inlineHelpText>
    <label>Team</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Team</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/Cost_Center_User__c.object-meta.xml
<CustomObject>
    <label>Cost Center User</label>
    <nameField>
        <displayFormat>CCU-{000000}</displayFormat>
        <label>Cost Center User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Center Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <referenceTo>Cost_Center__c</referenceTo>
    <relationshipLabel>Cost Center Users</relationshipLabel>
    <relationshipName>Cost_Center_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this the Primary Cost Center?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select User for Cost Center</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/MobileMessaging_SMS_Message__c.object-meta.xml
<CustomObject>
    <description>This object holds the text messages sent and received. by the contact</description>
    <label>MobileMessaging SMS Message</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MobileMessaging SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MobileMessaging SMS Messages</relationshipLabel>
    <relationshipName>Text_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>inbound</fullName>
            </value>
            <value>
                <fullName>outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>SMS Message content for incoming and outgoing messages</description>
    <label>Message Content</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sender</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MobileMessaging_SMS_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <description>Storing the sender name at the time of sending the message in case it was changed</description>
    <label>Sender Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Short_Message__c.field-meta.xml
<CustomField>
    <fullName>Short_Message__c</fullName>
    <label>Short Message</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/MobileMessaging_SMS_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/globalValueSets/Team.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Allocations</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Recruitment</fullName>
    </customValue>
    <description>Teams for Notifications</description>
    <masterLabel>Team</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

.vscode/allianceuat_compare/force-app/main/default/classes/MobileMessagingIncomingSMSCallbackTest.cls
@isTest
private class MobileMessagingIncomingSMSCallbackTest {
    static List<MobileMessaging_SMS_Message__c> messages = new List<MobileMessaging_SMS_Message__c>();

    // Helper method to create a test contact with a mobile phone number
    private static Contact createTestContact(String mobilePhone) {
        Contact testContact = new Contact(LastName = 'TestContact', MobilePhone = mobilePhone);
        insert testContact;
        return testContact;
    }

    private static List<MobileMessaging_SMS_Message__c> createData(Contact cont){
        List<MobileMessaging_SMS_Message__c> messages = new List<MobileMessaging_SMS_Message__c>{
            new MobileMessaging_SMS_Message__c(
                Contact__c = cont.Id,
                Message_Content__c = 'Test Message',
                Short_Message__c = 'Test Message',
                Status__c = 'queued',
                Direction__c = 'outbound',
                // Remote_Message_ID__c = 'test',
                Source__c = 'Contact',
                Sender__c =  UserInfo.getUserId(),
                Sender_Name__c = 'Test Sender'
            )
        };
        insert messages;
        return messages;
            
    }

    @testSetup
    static void setup() {
    //     String costCenter = 'Alliance Test One';
    //     Application_SMS_Configuration__mdt settings = SettingsProvider.getSettings(costCenter);
    Branch__c branch = new Branch__c(City__c = 'Adelaide', Branch_Name__c = 'Adelaide Allocations', Branch_Code__c = '1');
        insert branch;

        Cost_Center__c costCenter = new Cost_Center__c(
            Name = 'Alliance Test One', 
            Branch__c = branch.Id, 
            SMS_Cost_Center__c = 'Alliance_Nurse_Allocations', 
            Team__c = 'Allocations', 
            Public_Group__c = 'Adelaide_Nursing_Allocations');
        insert costCenter;

        Cost_Center_User__c costCenterUser = new Cost_Center_User__c(Cost_Center__c = costCenter.Id, User__c = UserInfo.getUserId(), Is_Primary__c = true);
        insert costCenterUser;
    }


    @isTest static void testHandleMessage() {
        //  create a test contact with a specific phone number
        String testPhone = '+61434567890';
        Contact testContact = createTestContact(testPhone);
        List<MobileMessaging_SMS_Message__c> messages = createData(testContact);
        // String costCenter = 'Alliance Test One';
        SMSSettings settings = SMSSettings.getInstance();

        // Simulate incoming SMS message data
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        // req.requestURI = 'https://allianceaustralia--dev.sandbox.my.salesforce-sites.com/smsintegration/services/apexrest/MobileMessagingIncomingSMS/';
        req.requestURI = '/services/apexrest/MobileMessagingIncomingSMS';
        // req.addHeader('x-messagemedia-auth', 'TWVzc2FnZU1lZGlhIEluYm91bmQgVG');
        req.addHeader('x-messagemedia-auth', settings.inboundToken);
        // req.addParameter('metadata_sf_id', 'a9t9t000000yVddAAE');
        // // req.addParameter('messageIdMM', 'BBB');
        // req.addParameter('message_id', 'BBB');
        // req.addParameter('reply_id', 'CCC');
        // req.addParameter('source_address', '+61434567890');
        // req.addParameter('destination_address', '+61445678901');
        // req.addParameter('message_content', 'Hello, this is a test message.');
        // req.addParameter('reply_content', 'This is the reply');

        // String jsonPayload='{"messages":[{"callback_url": "https://allianceaustralia--dev.sandbox.my.salesforce-sites.com/smsintegration/services/apexrest/MobileMessagingServiceStatusCallback", "delivery_report": true, "destination_number": "+1234567890", "format": "SMS", "message_expiry_timestamp": null, "message_flags": [] , "message_id": "5043771f-500d-45be-bd41-191de803b577", "metadata":{"salesforce_message_id": "a9t9t000000yVddAAE"}, "status": "queued"}]}';
        // String jsonPayload='{"metadata_sf_id": "a9t9t000000yVddAAE", "message_id": messages[0].Id, "reply_id": "CCC", "source_address": "+61434567890", "destination_address": "+61445678901", "message_content": "Hello, this is a test message.", "reply_content": "This is the reply"}';
        String jsonPayload='{"metadata_sf_id": "';
        jsonPayload+= messages[0].Id;
        jsonPayload+= '", "message_id": "491296d9-8077-46ec-8114-4eb4cf91d0e6", "reply_id": "CCC", "source_address": "+61434567890", "destination_address": "+61445678901", "message_content": "Hello, this is a test message.", "reply_content": "This is the reply"}';
        
        req.requestBody = Blob.valueof(jsonPayload); 

        // system.debug('MobileMessagingServiceStatusCallback req.requestBody: ' + req.requestBody.toString());

        // Set the simulated request in the RestContext
        RestContext.request = req;
        RestContext.response = res;
        // Set up the mock HTTP response generator
        // Test.setMock(HttpCalloutMock.class, new MobileMessagingServiceMock());

        // Act - call the method to handle the incoming message
        Test.startTest();
        MobileMessagingIncomingSMSCallback.handleMessage();
        Test.stopTest();

        // Assert - verify a new SMS message record was created and linked to the contact
        // List<MobileMessaging_SMS_Message__c> smsMessages = [SELECT Id, Contact__c FROM MobileMessaging_SMS_Message__c WHERE Contact__c = :testContact.Id];
        // System.assertEquals(1, smsMessages.size(), 'One SMS message should be created.');
        // System.assertEquals(testContact.Id, smsMessages[0].Contact__c, 'The SMS message should be linked to the test contact.');

        // Assert - verify the response contains empty TwiML
        // System.assertEquals('<?xml version="1.0" encoding="UTF-8"?><Response/>', res.responseBody.toString(), 'The response body should contain empty TwiML.');
    }

    @isTest static void testHandleErrorMessage() {
        //  create a test contact with a specific phone number
        String testPhone = '+61434567890';
        Contact testContact = createTestContact(testPhone);
        List<MobileMessaging_SMS_Message__c> messages = createData(testContact);
        SMSSettings settings = SMSSettings.getInstance();

        // Simulate incoming SMS message data
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        // req.requestURI = 'https://allianceaustralia--dev.sandbox.my.salesforce-sites.com/smsintegration/services/apexrest/MobileMessagingIncomingSMS/';
        req.requestURI = '/services/apexrest/MobileMessagingIncomingSMS';
        req.addHeader('x-messagemedia-auth', settings.inboundToken);
        String jsonPayload='{"metadata_sf_id": ';
        jsonPayload+= messages[0].Id;
        // jsonPayload+= '", "message_id": "491296d9-8077-46ec-8114-4eb4cf91d0e6", "reply_id": "CCC", "source_address": "+61434567890", "destination_address": "+61445678901", "message_content": "Hello, this is a test message.", "reply_content": "This is the reply"}';
        // jsonPayload+= '", "message_id": "491296d9-8077-46ec-8114-4eb4cf91d0e6", "reply_id": "CCC", "source_address": "+61999999999", "destination_address": "+61445678901", "message_content": "Hello, this is a test message.", "reply_content": "This is the reply"}';
        
        req.requestBody = Blob.valueof(jsonPayload); 

        // Set the simulated request in the RestContext
        RestContext.request = req;
        RestContext.response = res;
        // Set up the mock HTTP response generator
        // Test.setMock(HttpCalloutMock.class, new MobileMessagingServiceMock());

        // Act - call the method to handle the incoming message
        Test.startTest();
        MobileMessagingIncomingSMSCallback.handleMessage();
        Test.stopTest();

        // Assert - verify a new SMS message record was created and linked to the contact
        // List<MobileMessaging_SMS_Message__c> smsMessages = [SELECT Id, Contact__c FROM MobileMessaging_SMS_Message__c WHERE Contact__c = :testContact.Id];
        // System.assertEquals(1, smsMessages.size(), 'One SMS message should be created.');
        // System.assertEquals(testContact.Id, smsMessages[0].Contact__c, 'The SMS message should be linked to the test contact.');

        // Assert - verify the response contains empty TwiML
        // System.assertEquals('<?xml version="1.0" encoding="UTF-8"?><Response/>', res.responseBody.toString(), 'The response body should contain empty TwiML.');
    }

    // Additional tests might be needed if there are other branches or logic in the handleMessage method.
    private class MobileMessagingServiceMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(202); // Simulate a successful response
            res.setBody('{"messages":[{"callback_url": "https://allianceaustralia--dev.sandbox.my.salesforce-sites.com/smsintegration/services/apexrest/MobileMessagingServiceStatusCallback", "delivery_report": true, "destination_number": "+1234567890", "format": "SMS", "message_expiry_timestamp": null, "message_flags": [] , "message_id": "5043771f-500d-45be-bd41-191de803b577", "metadata":{"salesforce_message_id": "a9t9t000000yVddAAE"}, "status": "queued"}]}');
            return res;
        }
    }

    private class MobileMessagingServiceErrorMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(202); // Simulate a successful response
            res.setBody('{"messages":[{"callback_url": "https://allianceaustralia--dev.sandbox.my.salesforce-sites.com/smsintegration/services/apexrest/MobileMessagingServiceStatusCallback", "delivery_report": true, "destination_number": "+1234567890", "format": "SMS", "message_expiry_timestamp": null, "message_flags": [] , "message_id": "5043771f-500d-45be-bd41-191de803b577", "metadata":{"salesforce_message_id": "a9t9t000000yVddAAE"}, "status": "queued"}]}');
            return res;
        }
    }
}