.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/Application_SMS_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>X1218 Application SMS Configuration</label>
    <pluralLabel>Application SMS Configurations</pluralLabel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Account_SID__c</fullName>
    <label>Account SID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The api end point</description>
    <label>API Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Site_Domain_URL__c.field-meta.xml
<CustomField>
    <fullName>API_Site_Domain_URL__c</fullName>
    <label>API Site Domain URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Authentication_Token__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Token__c</fullName>
    <description>this is either the authentication token Auth Token or the API Token depending on the SMS provider</description>
    <label>Authentication Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Sender_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Phone_Number__c</fullName>
    <label>Sender Phone Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <label>SMS Cost Center</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/Cost_Center__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select Branch for the Cost Center</inlineHelpText>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cost Centers</relationshipLabel>
    <relationshipName>Cost_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <inlineHelpText>Enter the Public Group Name</inlineHelpText>
    <label>Public Group</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <inlineHelpText>Enter the Developer Name of the Application SMS Config Custom Metadata</inlineHelpText>
    <label>SMS Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <inlineHelpText>Select Team for Cost Center</inlineHelpText>
    <label>Team</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Team</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/Cost_Center_User__c.object-meta.xml
<CustomObject>
    <label>Cost Center User</label>
    <nameField>
        <displayFormat>CCU-{000000}</displayFormat>
        <label>Cost Center User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Center Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <referenceTo>Cost_Center__c</referenceTo>
    <relationshipLabel>Cost Center Users</relationshipLabel>
    <relationshipName>Cost_Center_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this the Primary Cost Center?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select User for Cost Center</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/globalValueSets/Team.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Allocations</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Recruitment</fullName>
    </customValue>
    <description>Teams for Notifications</description>
    <masterLabel>Team</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

.vscode/allianceuat_compare/force-app/main/default/classes/SettingsProviderTest.cls
@isTest
private class SettingsProviderTest {

    @isTest
    static void settingsProvider_success() {  
        // String costCenter = 'Alliance Test One';
        // DEV
        // String costCenter = 'Alliance_Nurse_Test';
        // UAT
        String costCenter = 'Alliance_Nurse_Allocations';
        // String costCenter = 'Test_SMS_Metadata';
        
        Test.startTest();
        Application_SMS_Configuration__mdt settings = SettingsProvider.getSettings(costCenter);
        Test.stopTest();
    }

    @isTest
    static void settingsProvider_error() {
        String costCenter = 'Incorrect';
        Boolean exceptionCaught = false;
        Test.startTest();
        try{
            Application_SMS_Configuration__mdt settings = SettingsProvider.getSettings(costCenter);
        } catch(Exception e){
            exceptionCaught = true;
        }
        Test.stopTest();
        System.Assert.isTrue(exceptionCaught, 'Didn\'t catch the expected exception');
    }

    @testSetup
    static void setupData() {
        // Insert test data for Contact, CustomNotificationType, and TextIUS_Settings__c
        // Application_SMS_Configuration__mdt smsMetadata = new Application_SMS_Configuration__mdt (
        //     DeveloperName = 'Test_SMS_Metadata',
        //     Label = 'Test Config',
        //     Account_SID__c = 'test_sid',
        //     Authentication_Token__c = 'test_token',
        //     Sender_Phone_Number__c = '+15005550006', // This is a magic number for testing purposes
        //     API_Endpoint__c = 'https://test.endpoint.com',
        //     API_Site_Domain_URL__c = 'https://test.callback.com'//,
        //     // IsActive__c = true
        // );
        // insert smsMetadata;

        Contact testContact = new Contact(FirstName = 'John', LastName = 'Doe', Phone = '1234567890',email='test332255@emailtest.com');
        insert testContact;

        Branch__c branch = new Branch__c(City__c = 'Adelaide', Branch_Name__c = 'Adelaide Allocations', Branch_Code__c = '1');
        insert branch;

        Cost_Center__c costCenter = new Cost_Center__c(
            Name = 'Alliance Test One', 
            Branch__c = branch.Id, 
            // SMS_Cost_Center__c = 'Test_SMS_Metadata', 
            SMS_Cost_Center__c = 'Alliance_Nurse_Allocations', 
            Team__c = 'Allocations', 
            Public_Group__c = 'Adelaide_Nursing_Allocations');
        insert costCenter;

        Cost_Center_User__c costCenterUser = new Cost_Center_User__c(Cost_Center__c = costCenter.Id, User__c = UserInfo.getUserId(), Is_Primary__c = true);
        insert costCenterUser;


        // Mock settings for TextIUS_Settings__c

        SMSSettings settings = SMSSettings.getInstance();

    }
}