.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/Application_SMS_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>X1218 Application SMS Configuration</label>
    <pluralLabel>Application SMS Configurations</pluralLabel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Account_SID__c</fullName>
    <label>Account SID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>The api end point</description>
    <label>API Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/API_Site_Domain_URL__c.field-meta.xml
<CustomField>
    <fullName>API_Site_Domain_URL__c</fullName>
    <label>API Site Domain URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Authentication_Token__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Token__c</fullName>
    <description>this is either the authentication token Auth Token or the API Token depending on the SMS provider</description>
    <label>Authentication Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Admin_Id__c</fullName>
    <label>Default Admin Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Admin_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Admin_Name__c</fullName>
    <label>Default Admin Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Default_Greetings_Message__c.field-meta.xml
<CustomField>
    <fullName>Default_Greetings_Message__c</fullName>
    <label>Default Greeting Message</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Inbound_Header__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Header__c</fullName>
    <label>Inbound Header</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Inbound_Token__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Token__c</fullName>
    <description>Token to confirm SMS and Delivery Reports are coming from SMS Provider</description>
    <label>Inbound Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Twilio</fullName>
            </value>
            <value>
                <fullName>TextUs</fullName>
            </value>
            <value>
                <fullName>MessageMedia</fullName>
                <default>true</default>
                <label>MessageMedia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/Sender_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Phone_Number__c</fullName>
    <label>Sender Phone Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Application_SMS_Configuration__mdt/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <label>SMS Cost Center</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/Cost_Center__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center__c/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <inlineHelpText>Enter the Developer Name of the Application SMS Config Custom Metadata</inlineHelpText>
    <label>SMS Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/Cost_Center_User__c.object-meta.xml
<CustomObject>
    <label>Cost Center User</label>
    <nameField>
        <displayFormat>CCU-{000000}</displayFormat>
        <label>Cost Center User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Center Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <referenceTo>Cost_Center__c</referenceTo>
    <relationshipLabel>Cost Center Users</relationshipLabel>
    <relationshipName>Cost_Center_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this the Primary Cost Center?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Cost_Center_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select User for Cost Center</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/User/fields/SMS_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SMS_Cost_Center__c</fullName>
    <description>Connect User to an SMS Cost Center</description>
    <inlineHelpText>Connect User to an SMS Cost Center</inlineHelpText>
    <label>SMS Cost Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extra Staff Adelaide Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Adelaide General</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury Allocations</fullName>
            </value>
            <value>
                <fullName>Extra Staff Albury General</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Adelaide Nursing General</fullName>
            </value>
            <value>
                <fullName>Perth Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Perth Nursing General</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing Allocations</fullName>
            </value>
            <value>
                <fullName>Brisbane Nursing General</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing  Allocations</fullName>
            </value>
            <value>
                <fullName>Sydney Nursing General</fullName>
            </value>
            <value>
                <fullName>Alliance Test One</fullName>
                <isActive>false</isActive>
                <label>Alliance Test One</label>
            </value>
            <value>
                <fullName>Alliance Test Two</fullName>
                <isActive>false</isActive>
                <label>Alliance Test Two</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/SMSSettings.cls
public class SMSSettings {
    public String providerType { get; private set; }
    public String authenticationToken { get; private set; }
    public String accountSID { get; private set; }
    public String senderPhoneNumber { get; private set; }
    public String apiEndpoint { get; private set; }
    public String apiSiteDomainUrl { get; private set; }
    public String defaultAdminId { get; private set; }
    public String defaultAdminName { get; private set; }
    public String defaultGreeting { get; private set; }
    public Boolean isActive { get; private set; }
    public String inboundHeader { get; private set; }
    public String inboundToken { get; private set; }

    private static final String TEXTUS_PROVIDER = 'TextUs';
    private static final String TWILIO_PROVIDER = 'Twilio';
    private static final String MM_PROVIDER = 'MessageMedia';

    private SMSSettings(Application_SMS_Configuration__mdt settings) {
        if (settings != null) {
            loadSettings(settings); // Generalized settings loading
        }
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getInstance(String costCenter) {
        // if(String.isBlank(costCenter)){
        //     costCenter = [SELECT SMS_Cost_Center__c from User where Id = :UserInfo.getUserId() limit 1].SMS_Cost_Center__c;
        // }
        // System.debug('SMSSettings getInstance(String costCenter) costCenter: ' + costCenter);
        Application_SMS_Configuration__mdt settings = SettingsProvider.getSettings(costCenter);
        SMSSettings smsSettings = new SMSSettings(settings);
        Map<String, Object> result = new Map<String, Object>();
        result.put('defaultGreeting', smsSettings.defaultGreeting);
        return result;
    }

    // @AuraEnabled(cacheable=true)
    public static SMSSettings getInstance() {
        // String costCenter = [SELECT SMS_Cost_Center__c from User where Id = :UserInfo.getUserId() limit 1].SMS_Cost_Center__c;
        String costCenter = [SELECT Cost_Center__r.SMS_Cost_Center__c from Cost_Center_User__c where User__c = :UserInfo.getUserId() AND Is_Primary__c = true limit 1].Cost_Center__r.SMS_Cost_Center__c;
        System.debug('SMSSettings getInstance costCenter: ' + costCenter);
        Application_SMS_Configuration__mdt settings = SettingsProvider.getSettings(costCenter);
        return new SMSSettings(settings);
    }

    private void loadSettings(Application_SMS_Configuration__mdt config) {
        // Load configuration settings
        providerType = config.Provider_Name__c;
        authenticationToken = config.Authentication_Token__c;
        accountSID = config.Account_SID__c;
        senderPhoneNumber = config.Sender_Phone_Number__c;
        apiEndpoint = config.API_Endpoint__c;
        apiSiteDomainUrl = config.API_Site_Domain_URL__c;
        defaultAdminId = config.Default_Admin_Id__c;
        defaultAdminName = config.Default_Admin_Name__c;
        defaultGreeting = config.Default_Greetings_Message__c;
        isActive = config.isActive__c;
        inboundHeader = config.Inbound_Header__c;
        inboundToken = config.Inbound_Token__c;
    }

    // public String apiToken { get; private set; }
    // public String senderPhoneNumber { get; private set; }
    // public String apiUrl { get; private set; }
    // public Integer smsEventDescriptionLength { get; private set; }
    // public String greetings { get; private set; }
    // public String adminId { get; private set; }
    // public String adminName { get; private set; }
    // public String textUsPrivateKey { get; private set; }

    // public SMSSettings() {
    //     // Load configuration from TextIUS_Settings Custom Settings
    //     TextIUS_Settings__c settings = SettingsProvider.getSettings();
    //     apiToken = settings.API_Token__c;
    //     senderPhoneNumber = settings.Sender_Phone_Number__c;
    //     apiUrl = settings.API_URL__c;
    //     smsEventDescriptionLength = (Integer) settings.SMS_Event_Description_Length__c;
    //     greetings = settings.Greetings__c;
    //     adminId = settings.Default_Admin_Id__c;
    //     adminName = settings.Default_Name__c;
    //     textUsPrivateKey = settings.textus_privatekey__c;
    // }

    // public static SMSSettings getInstance() {
    //     return new SMSSettings();
    // }
}