.vscode/allianceuat_compare/force-app/main/default/objects/SIM_General_Settings__c/SIM_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SIM General Settings</label>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/SIM_General_Settings__c/fields/Shiftmatch_Minimum_Interval_mins__c.field-meta.xml
<CustomField>
    <fullName>Shiftmatch_Minimum_Interval_mins__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Shiftmatch  Minimum Interval (mins)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/SIM_General_Settings__c/fields/Shiftmatch_Scheduler_Name__c.field-meta.xml
<CustomField>
    <fullName>Shiftmatch_Scheduler_Name__c</fullName>
    <defaultValue>&quot;ShiftMatchScheduler&quot;</defaultValue>
    <label>Shiftmatch Scheduler Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ShiftMatchScheduler.cls
global class ShiftMatchScheduler implements Schedulable {
    static final String jobName = 'ShiftMatchScheduler';
    static final SIM_General_Settings__c settings = SIM_General_Settings__c.getInstance();

    global void execute(SchedulableContext SC) {
        try {
            // Call the method to match shifts
            ShiftMatchManager sm = new ShiftMatchManager();
            sm.processShortfalls();
        } finally {
            rescheduleJob(settings.Shiftmatch_Scheduler_Name__c, Integer.valueOf(settings.Shiftmatch_Minimum_Interval_mins__c));
        }
    }

    private static void rescheduleJob(String jobName, Integer minutesFromNow) {
        List<CronTrigger> jobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :jobName];

        if (!jobs.isEmpty()) {
            System.abortJob(jobs[0].Id);
        }

        String cronExpression = generateCronExpression(minutesFromNow);
        System.schedule(jobName, cronExpression, new ShiftMatchScheduler());
    }

 
    @testVisible
    private static String generateCronExpression(Integer minutesFromNow) {       
        DateTime scheduledTime = DateTime.now().addMinutes(minutesFromNow);  
        Integer minute = scheduledTime.minute();  
        Integer hour = scheduledTime.hour();  
        Integer day = scheduledTime.day(); 
        Integer month = scheduledTime.month();  
        Integer year = scheduledTime.year();  

        return '0 ' + minute + ' ' + hour + ' ' + day + ' ' + month + ' ? ' + year; 
    } 
}