.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <inlineHelpText>Defines whether expenses are chargeable to the client, and what the type of charge is.</inlineHelpText>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always Charged - As Paid</fullName>
            </value>
            <value>
                <fullName>Not Charged</fullName>
            </value>
            <value>
                <fullName>On-charge with Margin (%)</fullName>
                <isActive>false</isActive>
                <label>On-charge with Margin (%)</label>
            </value>
            <value>
                <fullName>On-charge with Markup ($)</fullName>
                <isActive>false</isActive>
                <label>On-charge with Markup ($)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/Payroll_Tax_Exempt__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Tax_Exempt__c</fullName>
    <label>Payroll Tax Exempt?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes - Workcover Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/tc9_et__Timesheet_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet_Notification_Email__c</fullName>
    <label>Timesheet Notification Email</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tc9_pr__Pay_Advice_Email_Address</valueSetName>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Job__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/X1218_CreateBHConnectUserTest.cls
@isTest
private class X1218_CreateBHConnectUserTest {

    static Account acc;
    static Account invAcc;
    static Contact con;
    static Contact clientContact;
    static TR1__Application_V2__c testApplication;

    @testSetup
    static void setupTestData() {
        

        Branch__c branch = new Branch__c(Branch_Name__c = 'Test Branch', Branch_Code__c = 'TST', City__c = 'Test City');
        insert branch;

        acc = SIM_TestDataFactory.genTestAccount('Candidate Pool', 'Client', false);
        acc.Payroll_Tax_Exempt__c = 'No';
        acc.Approval_Type__c = 'Not Charged';
        insert acc;
        invAcc = SIM_TestDataFactory.genTestAccount('invoice entity', 'Client', false);
        invAcc.Payroll_Tax_Exempt__c = 'No';
        invAcc.Approval_Type__c = 'Not Charged';
        insert invAcc;        

        // NOTE set contact as client contact instead of candidate because of unknown validation rule
        // con = SIM_TestDataFactory.genTestContact('Ridge', acc, 'Client Contact', true);
        Id contactRT = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();

        con = new Contact(FirstName = 'tot', LastName = 'brown', AccountId = acc.Id, RecordTypeId = contactRT, tc9_et__Timesheet_Notification_Email__c = 'Primary', email='abc@abc.com');
        clientContact = new Contact(FirstName = 'Ridge2', LastName = 'grwon', AccountId = acc.Id, RecordTypeId = contactRT, tc9_et__Timesheet_Notification_Email__c = 'Primary', email='abc@abc.com');
        insert new List<Contact> {con, clientContact};        
        update con;

        // Create a Job
        Id jobRT = Schema.SObjectType.TR1__Job__c.getRecordTypeInfosByName().get('Sourcing Role').getRecordTypeId();
        TR1__Job__c testJob = new TR1__Job__c();
        testJob.Name = 'Test Job';
        testJob.RecordTypeId = jobRT;
        testJob.Branch__c = branch.Id;
        insert testJob;
        
        // Create an Application with an Applicant
        testApplication = new TR1__Application_V2__c(TR1__Applicant__c=con.Id, TR1__Job__c=testJob.Id);
        insert testApplication;
        system.debug(testApplication);  
        
    }
    
    @isTest
    static void testProcessSubStatus() {

        testApplication = [SELECT Id, TR1__Applicant__c FROM TR1__Application_V2__c LIMIT 1];
        system.debug(testApplication);

        Test.startTest();
        // Create Sub Status
        TR1__Sub_Status__c testSubStatus = new TR1__Sub_Status__c(
            TR1__Value__c = 'BH_Connect',
            TR1__ATS_Stage__c = 'Contracting',
            TR1__Is_Active__c = true,
            TR1__Application__c = testApplication.Id
        );
        insert testSubStatus;        

        User createdUser = [SELECT Id, ContactId FROM User WHERE Contact.Email = 'abc@abc.com' LIMIT 1];
        System.assertNotEquals(null, createdUser, 'User Created');
        Test.stopTest();

    }
}