.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Brand_c__c.field-meta.xml
<CustomField>
    <fullName>Brand_c__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nursing</fullName>
            </value>
            <value>
                <fullName>Rural &amp; Remote</fullName>
            </value>
            <value>
                <fullName>Extra Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Accounting Segment - Branches GL Department</inlineHelpText>
    <label>GL Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>tc9_bgl__Acc_Segments__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Assignment Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>tc9_bgl__Acc_Segments__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__CompetencyBundle__c/fields/Is_Role_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Is_Role_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If true, bundle only contains Items which are Roles. If false, bundle only contains items which are Skills.</inlineHelpText>
    <label>Is Role Bundle?</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Branch Name for Scheduler</description>
    <formula>Branch__r.Branch_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Name</label>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Role_OR_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Role_OR_Bundle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Role OR Bundle</label>
    <referenceTo>sirenum__CompetencyBundle__c</referenceTo>
    <relationshipLabel>Shifts (Role OR Bundle)</relationshipLabel>
    <relationshipName>Role_Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Shift__c/fields/Skill_Attribute_OR_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Skill_Attribute_OR_Bundle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill / Attribute OR Bundle</label>
    <referenceTo>sirenum__CompetencyBundle__c</referenceTo>
    <relationshipLabel>Shifts (Skill / Attribute OR Bundle)</relationshipLabel>
    <relationshipName>Skill_Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__Ticket__c/fields/Competency_Category__c.field-meta.xml
<CustomField>
    <fullName>Competency_Category__c</fullName>
    <description>Competency Category for the DLRS.</description>
    <formula>TEXT(sirenum__TicketType__r.Competency_Category__c)</formula>
    <inlineHelpText>Competency Category for the DLRS.</inlineHelpText>
    <label>Competency Category</label>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__TicketType__c/fields/Competency_Category__c.field-meta.xml
<CustomField>
    <fullName>Competency_Category__c</fullName>
    <label>Competency Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ID Doc</fullName>
            </value>
            <value>
                <fullName>Licence</fullName>
            </value>
            <value>
                <fullName>Mandatory Training</fullName>
            </value>
            <value>
                <fullName>Practical Training</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Client Induction</fullName>
            </value>
            <value>
                <fullName>Clearance</fullName>
            </value>
            <value>
                <fullName>Vaccination/Immunisation</fullName>
            </value>
            <value>
                <fullName>Skills</fullName>
            </value>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Paypoint</fullName>
            </value>
            <value>
                <fullName>Job Type</fullName>
            </value>
            <value>
                <fullName>Driving Licenses</fullName>
                <isActive>false</isActive>
                <label>Driving Licenses</label>
            </value>
            <value>
                <fullName>Exclusions</fullName>
                <isActive>false</isActive>
                <label>Exclusions</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Heath &amp; Safety</fullName>
                <isActive>false</isActive>
                <label>Heath &amp; Safety</label>
            </value>
            <value>
                <fullName>Inductions</fullName>
                <isActive>false</isActive>
                <label>Inductions</label>
            </value>
            <value>
                <fullName>Medical</fullName>
                <isActive>false</isActive>
                <label>Medical</label>
            </value>
            <value>
                <fullName>Office/Admin</fullName>
                <isActive>false</isActive>
                <label>Office/Admin</label>
            </value>
            <value>
                <fullName>Specialties</fullName>
                <isActive>false</isActive>
                <label>Specialties</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/sirenum__TicketType__c/fields/Is_Role_Competency__c.field-meta.xml
<CustomField>
    <fullName>Is_Role_Competency__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, indicates that the Competency is a Role. Else it is a Skill.</description>
    <label>Is Role Competency?</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/CustomRules_Test.cls
/*
 * Copyright Sirenum (c) 2021.
 */
@IsTest
private class CustomRules_Test {

    @IsTest
    static void testNoShifts() {
        List<sirenum.SirenumEngine.Shift> shifts = new List<sirenum.SirenumEngine.Shift>();
        CustomRules testClass = new CustomRules();
        List<sirenum__LogEntry__c> logEntries = testClass.execute(shifts);
        System.assertEquals(0, logEntries.size());
    }

    @IsTest
    static void testFail() {
        /*
        // Accounting System
        tc9_bgl__Acc_System_Setup__c accSystem = new tc9_bgl__Acc_System_Setup__c(Name='test 4');
        insert accSystem;

        // GL Department
        tc9_bgl__Acc_Segments__c glDept = new tc9_bgl__Acc_Segments__c(
                Name='test 3',
                tc9_bgl__Accounting_System__c = accSystem.Id
        );
        insert glDept;

        // Branch
        Branch__c branch = new Branch__c(
                Branch_Name__c='test5',
                Branch_Code__c='00A',
                GL_Department__c=glDept.Id,
                City__c='test',
                Brand_c__c = 'Nursing'
        );
        insert branch;

        //Client Account
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get('Client')
                .getRecordTypeId();
        Account account = new Account(
                Name = 'Test Account',
                RecordTypeId = clientRecordTypeId,
                Branch__c = branch.Id
        );
        insert account;


         */
        //########################################################################################################

        sirenum__CompetencyBundle__c roleBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle ROLE', Is_Role_Bundle__c=true);
        sirenum__CompetencyBundle__c skillBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle SKILL');
        insert new List<sirenum__CompetencyBundle__c>{roleBundle, skillBundle};

        sirenum__TicketType__c competencyRole1 = new sirenum__TicketType__c(
                Name='Nursing T1',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencyRole2 = new sirenum__TicketType__c(
                Name='Nursing T2',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencySkill1 = new sirenum__TicketType__c(
                Name='Reading'
        );
        sirenum__TicketType__c competencySkill2 = new sirenum__TicketType__c(
                Name='Writing'
        );
        insert new List<sirenum__TicketType__c>{competencyRole1, competencyRole2, competencySkill1, competencySkill2};

        sirenum__CompetencyBundleItem__c bundleItemRole1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemRole2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole2.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill2.Id
        );
        insert new List<sirenum__CompetencyBundleItem__c>{bundleItemRole1, bundleItemRole2, bundleItemSkill1, bundleItemSkill2};

        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact');
        insert contact;

        sirenum__Shift__c shift = new sirenum__Shift__c(
                sirenum__Contact__c = contact.Id,
                sirenum__Scheduled_Start_Time__c = Datetime.newInstance(2021, 1, 1, 9, 0, 0),
                sirenum__Scheduled_End_Time__c = Datetime.newInstance(2021, 1, 1, 17, 0, 0),
                Role_OR_Bundle__c = roleBundle.Id,
                Skill_Attribute_OR_Bundle__c = skillBundle.Id
        );

        sirenum.SirenumEngine.Shift engineShift = new sirenum.SirenumEngine.Shift(shift);
        engineShift.isChecked = true;
        CustomRules testClass = new CustomRules();
        List<sirenum__LogEntry__c> logEntries = testClass.execute(new List<sirenum.SirenumEngine.Shift>{engineShift});
        System.assertEquals(2, logEntries.size());

/*
        Contact con1 = new Contact(FirstName = 'Candy', LastName = 'Date 1', AccountId = account.Id);
        insert con1;
        sirenum__Shift__c shift1 = new sirenum__Shift__c(
                sirenum__Contact__c = con1.Id,
                sirenum__Scheduled_Start_Time__c = Datetime.newInstance(2021, 1, 1, 9, 0, 0),
                sirenum__Scheduled_End_Time__c = Datetime.newInstance(2021, 1, 1, 17, 0, 0)
        );
        sirenum__Shift__c shift2 = new sirenum__Shift__c(
                sirenum__Scheduled_Start_Time__c = Datetime.newInstance(2021, 1, 1, 9, 0, 0),
                sirenum__Scheduled_End_Time__c = Datetime.newInstance(2021, 1, 1, 17, 0, 0)
        );
        List<sirenum.SirenumEngine.Shift> shifts = new List<sirenum.SirenumEngine.Shift>{
                new sirenum.SirenumEngine.Shift(shift1),
                new sirenum.SirenumEngine.Shift(shift2)
        };
        shifts[0].isExcluded = true;
        CustomRules testClass = new CustomRules();
        List<sirenum__LogEntry__c> logEntries = testClass.execute(shifts);
        System.assertEquals(0, logEntries.size());

 */
    }

    @IsTest
    static void testPass1(){
        sirenum__CompetencyBundle__c roleBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle ROLE', Is_Role_Bundle__c=true);
        sirenum__CompetencyBundle__c skillBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle SKILL');
        insert new List<sirenum__CompetencyBundle__c>{roleBundle, skillBundle};

        sirenum__TicketType__c competencyRole1 = new sirenum__TicketType__c(
                Name='Nursing T1',
                Competency_Category__c = 'Job Type',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencyRole2 = new sirenum__TicketType__c(
                Name='Nursing T2',
                Competency_Category__c = 'Job Type',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencySkill1 = new sirenum__TicketType__c(
                Name='Reading',
                Competency_Category__c = 'Skills'
        );
        sirenum__TicketType__c competencySkill2 = new sirenum__TicketType__c(
                Name='Writing',
                Competency_Category__c = 'Skills'
        );
        insert new List<sirenum__TicketType__c>{competencyRole1, competencyRole2, competencySkill1, competencySkill2};

        sirenum__CompetencyBundleItem__c bundleItemRole1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemRole2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole2.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill2.Id
        );
        insert new List<sirenum__CompetencyBundleItem__c>{bundleItemRole1, bundleItemRole2, bundleItemSkill1, bundleItemSkill2};

        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact');
        insert contact;

        sirenum__Ticket__c roleTicket = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencyRole1.Id,
                sirenum__Owner__c = contact.Id
        );
        sirenum__Ticket__c skillTicket = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencySkill1.Id,
                sirenum__Owner__c = contact.Id
        );

        insert new List<sirenum__Ticket__c>{roleTicket, skillTicket};
        roleTicket.sirenum__Revoked__c = false;
        skillTicket.sirenum__Revoked__c = false;
        update new List<sirenum__Ticket__c>{roleTicket, skillTicket};

        sirenum__Shift__c shift = new sirenum__Shift__c(
                sirenum__Contact__c = contact.Id,
                sirenum__Scheduled_Start_Time__c = Datetime.newInstance(2021, 1, 1, 9, 0, 0),
                sirenum__Scheduled_End_Time__c = Datetime.newInstance(2021, 1, 1, 17, 0, 0),
                Role_OR_Bundle__c = roleBundle.Id,
                Skill_Attribute_OR_Bundle__c = skillBundle.Id
        );

        sirenum.SirenumEngine.Shift engineShift = new sirenum.SirenumEngine.Shift(shift);
        engineShift.isChecked = true;
        CustomRules testClass = new CustomRules();
        List<sirenum__LogEntry__c> logEntries = testClass.execute(new List<sirenum.SirenumEngine.Shift>{engineShift});
        System.assertEquals(0, logEntries.size());
    }

    @IsTest
    static void testPassMulti(){
        sirenum__CompetencyBundle__c roleBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle ROLE', Is_Role_Bundle__c=true);
        sirenum__CompetencyBundle__c skillBundle = new sirenum__CompetencyBundle__c(Name='Test Comp Bundle SKILL');
        insert new List<sirenum__CompetencyBundle__c>{roleBundle, skillBundle};

        sirenum__TicketType__c competencyRole1 = new sirenum__TicketType__c(
                Name='Nursing T1',
                Competency_Category__c = 'Job Type',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencyRole2 = new sirenum__TicketType__c(
                Name='Nursing T2',
                Competency_Category__c = 'Job Type',
                Is_Role_Competency__c = true
        );
        sirenum__TicketType__c competencySkill1 = new sirenum__TicketType__c(
                Name='Reading',
                Competency_Category__c = 'Skills'
        );
        sirenum__TicketType__c competencySkill2 = new sirenum__TicketType__c(
                Name='Writing',
                Competency_Category__c = 'Skills'
        );
        insert new List<sirenum__TicketType__c>{competencyRole1, competencyRole2, competencySkill1, competencySkill2};

        sirenum__CompetencyBundleItem__c bundleItemRole1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemRole2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = roleBundle.Id,
                sirenum__Competency__c = competencyRole2.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill1 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill1.Id
        );
        sirenum__CompetencyBundleItem__c bundleItemSkill2 = new sirenum__CompetencyBundleItem__c(
                sirenum__CompetencyBundle__c = skillBundle.Id,
                sirenum__Competency__c = competencySkill2.Id
        );
        insert new List<sirenum__CompetencyBundleItem__c>{bundleItemRole1, bundleItemRole2, bundleItemSkill1, bundleItemSkill2};

        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact');
        insert contact;

        sirenum__Ticket__c roleTicket1 = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencyRole1.Id,
                sirenum__Owner__c = contact.Id
        );
        sirenum__Ticket__c roleTicket2 = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencyRole2.Id,
                sirenum__Owner__c = contact.Id
        );
        sirenum__Ticket__c skillTicket1 = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencySkill1.Id,
                sirenum__Owner__c = contact.Id
        );
        sirenum__Ticket__c skillTicket2 = new sirenum__Ticket__c(
                sirenum__TicketType__c = competencySkill2.Id,
                sirenum__Owner__c = contact.Id
        );
        insert new List<sirenum__Ticket__c>{roleTicket1, roleTicket2, skillTicket1, skillTicket2};
        roleTicket1.sirenum__Revoked__c = false;
        skillTicket1.sirenum__Revoked__c = false;
        roleTicket2.sirenum__Revoked__c = false;
        skillTicket2.sirenum__Revoked__c = false;
        update new List<sirenum__Ticket__c>{roleTicket1, skillTicket1, roleTicket2, skillTicket2};

        sirenum__Shift__c shift = new sirenum__Shift__c(
                sirenum__Contact__c = contact.Id,
                sirenum__Scheduled_Start_Time__c = Datetime.newInstance(2021, 1, 1, 9, 0, 0),
                sirenum__Scheduled_End_Time__c = Datetime.newInstance(2021, 1, 1, 17, 0, 0),
                Role_OR_Bundle__c = roleBundle.Id,
                Skill_Attribute_OR_Bundle__c = skillBundle.Id
        );

        sirenum.SirenumEngine.Shift engineShift = new sirenum.SirenumEngine.Shift(shift);
        engineShift.isChecked = true;
        CustomRules testClass = new CustomRules();
        List<sirenum__LogEntry__c> logEntries = testClass.execute(new List<sirenum.SirenumEngine.Shift>{engineShift});
        System.assertEquals(0, logEntries.size());
    }
}