.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Custom records used to drives General Ledger dimensions beyond a natural account.</description>
    <label>Branch</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Branch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <description>Unique code for the branch.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique code for the branch.</inlineHelpText>
    <label>Branch Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Name of the branch.</description>
    <inlineHelpText>Name of the branch.</inlineHelpText>
    <label>Branch Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch__c/fields/Branch_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Phone_Number__c</fullName>
    <label>Branch Phone Number</label>
    <type>Phone</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch_Email__c/Branch_Email__c.object-meta.xml
<CustomObject>
    <label>Branch Email</label>
    <nameField>
        <label>Branch Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/Branch_Email__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branch Emails</relationshipLabel>
    <relationshipName>Branch_Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <inlineHelpText>AHPRA number, otherwise leave blank if not relevant</inlineHelpText>
    <label>AHPRA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fixed Assets</relationshipLabel>
    <relationshipName>Fixed_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Fixed Assets</relationshipLabel>
    <relationshipName>Fixed_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch_Email__c.field-meta.xml
<CustomField>
    <fullName>Branch_Email__c</fullName>
    <inlineHelpText>Email address of branch for back of ID badge</inlineHelpText>
    <label>Branch Email</label>
    <type>Email</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Branch_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Phone_Number__c</fullName>
    <inlineHelpText>To appear on back of ID badge</inlineHelpText>
    <label>Branch Phone Number</label>
    <type>Phone</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <inlineHelpText>Select which brand for appropriate logo for ID badge</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nursing</fullName>
            </value>
            <value>
                <fullName>Extra Staff</fullName>
            </value>
            <value>
                <fullName>R&amp;R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>Position title to appear on the front of the ID badge</inlineHelpText>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <inlineHelpText>Preferred name to appear on the front of the badge</inlineHelpText>
    <label>Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/TR1__Fixed_Assets__c/recordTypes/ID_Badge.recordType-meta.xml
<RecordType>
    <fullName>ID_Badge</fullName>
    <active>true</active>
    <label>ID Badge</label>
</RecordType>

.vscode/allianceuat_compare/force-app/main/default/classes/PDFGenerateIDBadge_test.cls
@isTest
private class PDFGenerateIDBadge_test {

    public static Account acc = new Account();
    public static Contact cont = new Contact();
    public static TR1__Fixed_Assets__c idBadge = new TR1__Fixed_Assets__c();
    public static Branch__c branch = new Branch__c();

    @isTest
    static void generateIDBadgeTest() {
        createData();
        System.Test.startTest();
        PDFGenerateIDBadge.createIDBadgeSingle(idBadge.Id);
               
        System.Test.stopTest();
    }

    public static void createData(){
        acc = SIM_TestDataFactory.genTestAccount('accountName', 'Candidate Pool', true);
        cont = SIM_TestDataFactory.genTestContact('Brown', acc.Id, 'Candidate', false);
        // cont = SIM_TestDataFactory.genTestContact('Brown', acc.Id, 'Candidate Contact', false);
        cont.FirstName = 'Charlie';
        cont.Email = '1218-SFDC-Support@1218global.com';
        insert cont; 

        branch = new Branch__c(
            Branch_Name__c = 'Test Branch',
            Branch_Code__c = 'A',
            City__c = 'Sydney'
        );
        insert branch;

        idBadge = new TR1__Fixed_Assets__c(
            Assigned__c = cont.Id,
            Preferred_Name__c = 'Charlie',
            AHPRA_Number__c = 'NUM00001', 
            Branch__c = branch.Id, 
            Branch_Email__c = 'testemail@test.com',
            Branch_Phone_Number__c = '0401010101',
            Brand__c = 'Nursing',
            RecordTypeId = Schema.SObjectType.TR1__Fixed_Assets__c.getRecordTypeInfosByDeveloperName().get('ID_Badge').getRecordTypeId(),
            Position__c = 'Nursing Assistant');
        insert idBadge;

    }
}