.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/tc9_pr__Available_Payment_Methods__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Available_Payment_Methods__c</fullName>
    <description>The Payment Methods that are available to use by the Payment Entity</description>
    <inlineHelpText>The Payment Methods that are available to use by the Payment Entity</inlineHelpText>
    <label>Available Payment Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payee Australian Bank</fullName>
            </value>
            <value>
                <fullName>Payee International Bank</fullName>
            </value>
            <value>
                <fullName>Payee Cheque</fullName>
            </value>
            <value>
                <fullName>Payee Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/tc9_pr__Maximum_Payment_Distributions__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Maximum_Payment_Distributions__c</fullName>
    <description>The maximum number of payment distributions allowed per Payee for the Payment Entity. A global maximum of 5 applies.</description>
    <inlineHelpText>The maximum number of payment distributions allowed per Payee for the Payment Entity. A global maximum of 5 applies.</inlineHelpText>
    <label>Maximum Payment Distributions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>7</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/Account/fields/TR1__Status__c.field-meta.xml
<CustomField>
    <fullName>TR1__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Terms &amp; Conditions</fullName>
            </value>
            <value>
                <fullName>Credit Check</fullName>
            </value>
            <value>
                <fullName>Invoicing &amp; Billing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportLog__c/ShiftImportLog__c.object-meta.xml
<CustomObject>
    <label>Shift Import Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Shift Import Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shift Import Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/ShiftImportSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Shift Import Settings</label>
</CustomObject>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Allow_Delete_Results__c.field-meta.xml
<CustomField>
    <fullName>Allow_Delete_Results__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Delete Results</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Allow_Quick_Create__c.field-meta.xml
<CustomField>
    <fullName>Allow_Quick_Create__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Quick Create</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Default_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Default_Cancellation_Reason__c</fullName>
    <inlineHelpText>Must be present in Picklist Value Sets -&gt; Cancellation Reasons for versions of sirenum higher than 1.185</inlineHelpText>
    <label>Default Cancellation Reason</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Import_Demand__c.field-meta.xml
<CustomField>
    <fullName>Import_Demand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Import Shift Demands</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Import_Shifts__c.field-meta.xml
<CustomField>
    <fullName>Import_Shifts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Import Shifts</label>
    <type>Checkbox</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Match_Accounts__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <label>Match: Accounts</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Match_Contacts__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <inlineHelpText>API name of a field to be used for the tool to match contacts (defaults to Email)</inlineHelpText>
    <label>Match: Contacts</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Job_Roles__c.field-meta.xml
<CustomField>
    <fullName>Match_Job_Roles__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <inlineHelpText>API name of field to be used to match Job Roles. Defaults to Name</inlineHelpText>
    <label>Match: Job Roles</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Rotas__c.field-meta.xml
<CustomField>
    <fullName>Match_Rotas__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <inlineHelpText>API field name to match by</inlineHelpText>
    <label>Match: Rotas</label>
    <length>244</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Shifts__c.field-meta.xml
<CustomField>
    <fullName>Match_Shifts__c</fullName>
    <defaultValue>&quot;sirenum__FMS_Shift_ID__c&quot;</defaultValue>
    <label>Match: Shifts</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/ShiftImportSettings__c/fields/Match_Sites__c.field-meta.xml
<CustomField>
    <fullName>Match_Sites__c</fullName>
    <defaultValue>&quot;Name&quot;</defaultValue>
    <inlineHelpText>API field name used to match Sites. Defaults to Name</inlineHelpText>
    <label>Match: Sites</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ShiftImportTool_Test.cls
@isTest
public class ShiftImportTool_Test {

    private static sirenum__Site__c site;
    private static sirenum__Rota__c rota;
    private static sirenum__Team__c team;
    private static sirenum__Team__c team2;    
    private static sirenum__Team__c team3;    
    private static Contact con;

    private static sirenum__Site__c site2;
    private static sirenum__Rota__c rota2;
    private static Contact con2;

    private static ShiftImportLog__c itdc;
    private static Account acc;
    private static ShiftImportSettings__c its;

    private static contract contract;
    private static sirenum__Payroll_Cycle__c paycycle;

    private static void createTestData() {
        //TEST RECORDS  
        site = new sirenum__Site__c(Name = 'test Site');
        insert site;
        rota = new sirenum__Rota__c(Name = 'test ROTA');
        insert rota;
        acc = new Account(Name = 'Test Account', TR1__Status__c = 'Live', tc9_pr__Available_Payment_Methods__c = 'Payee Australian Bank', tc9_pr__Maximum_Payment_Distributions__c = '1');
        insert acc;
        con = new Contact(FirstName = 'John', LastName = 'User', Email = 'test@sirenum.com', MobilePhone = '07583331473', AccountId = acc.Id);
        insert con;
        paycycle = new sirenum__Payroll_Cycle__c(Name = 'Sunday - Monday', sirenum__CyclePeriodUnits__c = 'Weeks', sirenum__periodLength__c = 1, sirenum__StartingDate__c = system.today());
        insert paycycle;
        contract = new Contract(Name = 'BBF Hull', AccountId = acc.Id, Status = 'Draft', StartDate = date.today(), ContractTerm = 1);
        insert contract;

        //Secondary Records
        site2 = new sirenum__Site__c(Name = 'test Site2');
        insert site2;
        rota2 = new sirenum__Rota__c(Name = 'test ROTA2');
        insert rota2;
        con2 = new Contact(FirstName = 'Jane', LastName = 'OtherUser', Email = 'test@sirenum.com', MobilePhone = '07583331473', AccountId = acc.Id);
        insert con2;

        Schema.DescribeFieldResult cancellationReasonsDescribe = sirenum__Shift__c.sirenum__CancellationReason__c.getDescribe();
        Schema.SObjectField T = cancellationReasonsDescribe.getSobjectField();
        List<PicklistEntry> entries = T.getDescribe().getPicklistValues();

        team = new sirenum__Team__c(Name = 'test TEAM');
        insert team;
        team2 = new sirenum__Team__c(Name = 'test TEAM2');
        insert team2;        


        //DB Object
        itdc = new ShiftImportLog__c();

        //Settings
        its = new ShiftImportSettings__c();
        its.Match_Accounts__c = 'Name';
        its.Match_Contacts__c = 'Name';
        its.Match_Job_Roles__c = 'Name';
        its.Match_Rotas__c = 'Name';
        its.Match_Shifts__c = 'sirenum__FMS_Shift_ID__c';
        its.Match_Sites__c = 'Name';
        its.Default_Cancellation_Reason__c = entries.get(0).getValue();

        insert its;

    }

    static testmethod void testFailures() {
        createTestData();
        //Settings
        its.Allow_Delete_Results__c = true;
        its.Allow_Quick_Create__c = true;
        its.Import_Demand__c = true;
        its.Import_Shifts__c = true;
        its.SetupOwnerId = UserInfo.getOrganizationId();
        update its;

        apexpages.StandardController sc = new apexPages.StandardController(itdc);
        ShiftImportTool controller = new ShiftImportTool(sc);

        //Improt shift demand against a worker
        String jsnString = '{"importFile": [{'+
                                '"REFERENCE": "1234",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "John User",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';

        List<ShiftImportTool.infoRow> returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
        System.assertEquals(true, returnRows[0].rawInfoMessage.containsIgnoreCase('cannot be assigned to'));

        //Now insert the demand
        jsnString = '{"importFile": [{'+
                                '"REFERENCE": "1234",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';
        returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
        System.assertEquals('Inserted Shift Demand [Requirement]', returnRows[0].infoMessage);

        //Attempt to update shift demand - fail due to duplicate shifts with the reference number
        jsnString = '{"importFile": [{'+
                                '"REFERENCE": "1234",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';
        returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());

        //Duplicate Sites/Jobs/Rotas/Contacts
        sirenum__Site__c site3 = new sirenum__Site__c(Name = 'test Site');
        insert site3;
        sirenum__Rota__c rota3 = new sirenum__Rota__c(Name = 'test ROTA');
        insert rota3;
        team3 = new sirenum__Team__c(Name = 'test TEAM');
        insert team3;
        Contact con3 = new Contact(FirstName = 'John', LastName = 'User', Email = 'test2@sirenum.com', MobilePhone = '07583331470', AccountId = acc.Id);
        insert con3;

        jsnString = '{"importFile": [{'+
                                '"REFERENCE": "12345",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';
        returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
    }

    static testmethod void testDataIntegrity() {
        createTestData();
        //Settings
        its.Allow_Delete_Results__c = true;
        its.Allow_Quick_Create__c = true;
        its.Import_Demand__c = true;
        its.Import_Shifts__c = true;
        its.SetupOwnerId = UserInfo.getOrganizationId();
        update its;

        apexpages.StandardController sc = new apexPages.StandardController(itdc);
        ShiftImportTool controller = new ShiftImportTool(sc);

        //Bad or missing data
        String jsnString = '{"importFile": [{'+
                                '"REFERENCE": "12345",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';
        List<ShiftImportTool.infoRow> returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
        // System.assertEquals(true, returnRows[0].rawInfoMessage.containsIgnoreCase('Invalid Date:'));
        System.assertEquals(true, returnRows[0].rawInfoMessage.containsIgnoreCase('No start time'));

        //Bad end time
        jsnString = '{"importFile": [{'+
                        '"REFERENCE": "12345",'+
                        '"PO NUMBER": "12345",'+
                        '"BOOKING DATE": "2016-01-01",'+
                        '"SCHEDULED DATE": "2016-01-01",'+
                        '"WORKER": "",'+
                        '"SITE": "test Site",'+
                        '"ROTA": "test ROTA",'+
                        '"JOB ROLE": "test TEAM",'+
                        '"START": "",'+
                        '"END": "",'+
                        '"REQUIRED SHIFTS": "2",'+
                        '"COMMENTS": "A comment",'+
                        '"CANCELLED": "FALSE",'+
                        '"TYPE": "PM",'+
                        '"BOOKED BY": "BOOKED BY"'+
                    '}]}';
        returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
        System.assertEquals(false, returnRows[0].rawInfoMessage.containsIgnoreCase('Bad End time'));
        //Bad end time
        jsnString = '{"importFile": [{'+
                        '"REFERENCE": "12345",'+
                        '"PO NUMBER": "12345",'+
                        '"BOOKING DATE": "2016-01-01",'+
                        '"SCHEDULED DATE": "2016-01-01",'+
                        '"WORKER": "",'+
                        '"SITE": "test Site",'+
                        '"ROTA": "test ROTA",'+
                        '"JOB ROLE": "test TEAM",'+
                        '"START": "A",'+
                        '"END": "17:30",'+
                        '"REQUIRED SHIFTS": "2",'+
                        '"COMMENTS": "A comment",'+
                        '"CANCELLED": "FALSE",'+
                        '"TYPE": "PM",'+
                        '"BOOKED BY": "BOOKED BY"'+
                    '}]}';
        returnRows = ShiftImportTool.parse(jsnString);
        System.assertEquals(1, returnRows.size());
        System.assertEquals(true, returnRows[0].rawInfoMessage.containsIgnoreCase('Bad Start time'));

        its.Match_Shifts__c = 'Name';
        update its;
        //Bad Field
        jsnString = '{"importFile": [{'+
                                '"REFERENCE": "12345",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "B",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';
        try {
            returnRows = ShiftImportTool.parse(jsnString);
        } catch (Exception e) {
            System.assertEquals(true, e.getMessage().containsIgnoreCase('Field Name is not editable'));
        }
    }

    static testmethod void testBadInsert() {
        createTestData();
        //Settings
        its.Allow_Delete_Results__c = true;
        its.Allow_Quick_Create__c = true;
        its.Import_Demand__c = true;
        its.Import_Shifts__c = true;
        its.SetupOwnerId = UserInfo.getOrganizationId();
        update its;

        apexpages.StandardController sc = new apexPages.StandardController(itdc);
        ShiftImportTool controller = new ShiftImportTool(sc);

        //Bad or missing data
        //Now insert the demand
        String jsnString = '{"importFile": [{'+
                                '"REFERENCE": "1234",'+
                                '"PO NUMBER": "12345",'+
                                '"BOOKING DATE": "2016-01-01",'+
                                '"SCHEDULED DATE": "2016-01-01",'+
                                '"WORKER": "",'+
                                '"SITE": "test Site",'+
                                '"ROTA": "test ROTA",'+
                                '"JOB ROLE": "test TEAM",'+
                                '"START": "09:30",'+
                                '"END": "17:30",'+
                                '"REQUIRED SHIFTS": "2",'+
                                '"COMMENTS": "A comment",'+
                                '"CANCELLED": "FALSE",'+
                                '"TYPE": "PM",'+
                                '"BOOKED BY": "BOOKED BY"'+
                            '}]}';

        try {
            ShiftImportTool.throwTestException = true;
            List<ShiftImportTool.infoRow> returnRows = ShiftImportTool.parse(jsnString);
        } catch (Exception e) {
            System.assertEquals(true, e.getMessage().containsIgnoreCase('Shift Insert Error'));
        }
    }


}