.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Ability_to_carry_out_daily_routines_1_3__c.field-meta.xml
<CustomField>
    <fullName>Ability_to_carry_out_daily_routines_1_3__c</fullName>
    <inlineHelpText>If 1-3 - Please tell us a bit more</inlineHelpText>
    <label>Ability to carry out daily routines -1-3</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Adhering_to_OHS_guidelines__c.field-meta.xml
<CustomField>
    <fullName>Adhering_to_OHS_guidelines__c</fullName>
    <inlineHelpText>Does “applicant” adhere to OHS guidelines (e.g. infection control, PPE, security, handwashing &amp; lifting)</inlineHelpText>
    <label>Adhering to OHS guidelines</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Adhering_to_OHS_guidelines_No__c.field-meta.xml
<CustomField>
    <fullName>Adhering_to_OHS_guidelines_No__c</fullName>
    <inlineHelpText>If no - Please tell us a bit more</inlineHelpText>
    <label>Adhering to OHS guidelines - No</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/AHPRA_based_investigations_or_disputes__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_based_investigations_or_disputes__c</fullName>
    <inlineHelpText>Has candidate been subject to any Facility or AHPRA based investigations, disputes or complaints?</inlineHelpText>
    <label>AHPRA based investigations or disputes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/AHPRA_based_investigations_yes__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_based_investigations_yes__c</fullName>
    <inlineHelpText>If yes - Please tell us a bit more</inlineHelpText>
    <label>AHPRA based investigations - yes</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Applicant_can_work_unsupervised__c.field-meta.xml
<CustomField>
    <fullName>Applicant_can_work_unsupervised__c</fullName>
    <inlineHelpText>Would you say “applicant” performance is consistent &amp; are they able to work well unsupervised?</inlineHelpText>
    <label>Applicant can work unsupervised</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Applicant_s_duties_responsibilies__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_duties_responsibilies__c</fullName>
    <inlineHelpText>What were “applicant” clinical duties &amp; responsibilities in this role?</inlineHelpText>
    <label>Applicant&apos;s duties &amp; responsibilies</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Clinical_Skill_More_Information__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Skill_More_Information__c</fullName>
    <inlineHelpText>If needing assistance or not applicable - Please tell us a bit more</inlineHelpText>
    <label>Clinical Skill - More Information</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Clinical_Skills__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Skills__c</fullName>
    <inlineHelpText>How would you rate the clinical skills demonstrated by the candidate in this role?</inlineHelpText>
    <label>Clinical Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highly skilled</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Needing assistance</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Communication_Documentation_Skills__c.field-meta.xml
<CustomField>
    <fullName>Communication_Documentation_Skills__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” communication / documentation skills (if electronic notes are used, can you comment on their effectiveness)</inlineHelpText>
    <label>Communication / Documentation Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Communication_Skills_1_3__c.field-meta.xml
<CustomField>
    <fullName>Communication_Skills_1_3__c</fullName>
    <inlineHelpText>If 1-3 - Please tell us a bit more</inlineHelpText>
    <label>Communication Skills - 1 - 3</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Dealing_with_emergency_situation_1_3__c.field-meta.xml
<CustomField>
    <fullName>Dealing_with_emergency_situation_1_3__c</fullName>
    <inlineHelpText>If 1-3 - Please tell us a bit more</inlineHelpText>
    <label>Dealing with emergency situation - 1-3</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Dealing_with_emergency_situation__c.field-meta.xml
<CustomField>
    <fullName>Dealing_with_emergency_situation__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” ability to deal with emergency situations &amp; do you have confidence they are able to accurately assess, diagnose &amp; treat in these situations?</inlineHelpText>
    <label>Dealing with emergency situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Describe_clinical_community_setting__c.field-meta.xml
<CustomField>
    <fullName>Describe_clinical_community_setting__c</fullName>
    <inlineHelpText>Can you briefly describe the clinical / community setting in which “applicant” worked (demographics/specialities etc)</inlineHelpText>
    <label>Describe clinical/ community setting</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Handling_medication_administration__c.field-meta.xml
<CustomField>
    <fullName>Handling_medication_administration__c</fullName>
    <inlineHelpText>Does “applicant” demonstrate due care &amp; attention to medication administration/ distribution? Any errors to your knowledge?</inlineHelpText>
    <label>Handling medication administration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Handling_medication_administration_No__c.field-meta.xml
<CustomField>
    <fullName>Handling_medication_administration_No__c</fullName>
    <inlineHelpText>If no - Please tell us a bit more</inlineHelpText>
    <label>Handling medication administration  --No</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Happy_to_provide_References__c.field-meta.xml
<CustomField>
    <fullName>Happy_to_provide_References__c</fullName>
    <inlineHelpText>Are you happy to provide a reference for your time working with the candidate?</inlineHelpText>
    <label>Happy to provide References?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Permission_to_disclose_reference_check__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_disclose_reference_check__c</fullName>
    <inlineHelpText>Do you give permission for us to disclose this reference check to candidate if requested?</inlineHelpText>
    <label>Permission to disclose reference check</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/permission_to_disclose_this_reference__c.field-meta.xml
<CustomField>
    <fullName>permission_to_disclose_this_reference__c</fullName>
    <inlineHelpText>Do we have your permission to disclose this reference to selected potential employers for the duration of #first_name#&apos;s employment with our agency?</inlineHelpText>
    <label>Permission to disclose this reference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Rating_applicant_s_ability_to_do_tasks__c.field-meta.xml
<CustomField>
    <fullName>Rating_applicant_s_ability_to_do_tasks__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” ability to carry out their daily duties (time management, ability to prioritise etc)</inlineHelpText>
    <label>Rating applicant&apos;s ability to do tasks</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Rehire_applicant_further_comments__c.field-meta.xml
<CustomField>
    <fullName>Rehire_applicant_further_comments__c</fullName>
    <inlineHelpText>Would you rehire “applicant” &amp; do you have any further comments you’d like to make?</inlineHelpText>
    <label>Rehire applicant &amp; further comments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Rehire_applicant_further_comments_Yes__c.field-meta.xml
<CustomField>
    <fullName>Rehire_applicant_further_comments_Yes__c</fullName>
    <inlineHelpText>If yes - Please tell us a bit more</inlineHelpText>
    <label>Rehire applicant &amp; further comments -Yes</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Work_well_unsupervised_No__c.field-meta.xml
<CustomField>
    <fullName>Work_well_unsupervised_No__c</fullName>
    <inlineHelpText>If no - Please tell us a bit more</inlineHelpText>
    <label>Worked well unsupervised - (If No)</label>
    <type>TextArea</type>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Worked_well_unsupervised__c.field-meta.xml
<CustomField>
    <fullName>Worked_well_unsupervised__c</fullName>
    <inlineHelpText>Did the candidate work well unsupervised?</inlineHelpText>
    <label>Worked well unsupervised?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ReferenceCheckExtension.cls
public with sharing class ReferenceCheckExtension {
    // Put variables here
    public b3o__Reference__c record {get;set;}

    public ReferenceCheckExtension(ApexPages.StandardController stdController) {
        System.debug(LOGGINGLEVEL.ERROR, stdController.getId());
        
        this.record = [SELECT Id, 
            Name, 
            b3o__First_Name_Referee__c, 
            b3o__Last_Name_Referee__c, 
            b3o__Contact__r.FirstName, 
            b3o__Contact__r.LastName, 
            b3o__Position_Referee__c, 
            b3o__Email_Referee__c, 
            b3o__Phone_Referee__c,
            Happy_to_provide_References__c, 
            permission_to_disclose_this_reference__c, 
            Permission_to_disclose_reference_check__c, 
            AHPRA_based_investigations_or_disputes__c, 
            AHPRA_based_investigations_yes__c, 
            Describe_clinical_community_setting__c, 
            Applicant_s_duties_responsibilies__c, 
            Rating_applicant_s_ability_to_do_tasks__c,
            Ability_to_carry_out_daily_routines_1_3__c, 
            Applicant_can_work_unsupervised__c, 
            Work_well_unsupervised_No__c, 
            Worked_well_unsupervised__c, 
            Communication_Documentation_Skills__c, 
            Communication_Skills_1_3__c, 
            Clinical_Skills__c, 
            Clinical_Skill_More_Information__c, 
            Handling_medication_administration__c, 
            Handling_medication_administration_No__c, 
            Dealing_with_emergency_situation__c, 
            Dealing_with_emergency_situation_1_3__c, 
            Adhering_to_OHS_guidelines__c, 
            Adhering_to_OHS_guidelines_No__c, 
            Rehire_applicant_further_comments__c, 
            Rehire_applicant_further_comments_Yes__c
            FROM b3o__Reference__c 
            WHERE Id =:stdController.getId()];
    }

    public String firstNameApos {
        get {
            return this.record.b3o__Contact__r.FirstName + '\'s' ;
        }
    } 

    public boolean ratingDailyTasks {
        get {
            boolean result;
            switch on this.record.Rating_applicant_s_ability_to_do_tasks__c{
                when '1', '2', '3'{
                    result = true;
                }
                when '4', '5'{
                    result = false;
                }
            }
            return result;
        }
    } 

    public boolean ratingCommSkills {
        get {
            boolean result;
            switch on this.record.Communication_Documentation_Skills__c{
                when '1', '2','3'{
                    result = true;
                }
                when '4', '5'{
                    result = false;
                }
            }
            return result;
        }
    } 

    
    public boolean ratingClinicalSkills {
        get {
            boolean result;
            switch on this.record.Clinical_Skills__c{
                when 'Needing assistance'{
                    result = true;
                }
                when else{
                    result = false;
                }
            }
            return result;
        }
    } 

    public boolean ratingEmergencySits {
        get {
            boolean result;
            switch on this.record.Dealing_with_emergency_situation__c{
                when '1', '2','3'{
                    result = true;
                }
                when '4', '5'{
                    result = false;
                }
            }
            return result;
        }
    } 

    public String respProvideRefs{
        get {
            String result = responseYesNo(this.record.Happy_to_provide_References__c);
            return result;
        }
    }

    public String respDiscloseRefs{
        get {
            String result = responseYesNo(this.record.Permission_to_disclose_reference_check__c);
            return result;
        }
    }

    public String respAHPRAInvDisps{
        get {
            String result = responseYesNo(this.record.AHPRA_based_investigations_or_disputes__c);
            return result;
        }
    }

    public String respApplUnsupervised{
        get {
            String result = responseYesNo(this.record.Applicant_can_work_unsupervised__c);
            return result;
        }
    }

    public String respHandlingMeds{
        get {
            String result = responseYesNo(this.record.Handling_medication_administration__c);
            return result;
        }
    }

    public String respOHSGuidelines{
        get {
            String result = responseYesNo(this.record.Adhering_to_OHS_guidelines__c);
            return result;
        }
    }
    
    public String respRehireAppl{
        get {
            String result = responseYesNo(this.record.Rehire_applicant_further_comments__c);
            return result;
        }
    }

    private String responseYesNo(String reply){
            String result = '';
            switch on reply{
                when 'Yes'{
                    result += '<b>Yes</b> | No' ;     
                }
                when 'No'{
                    result += 'Yes | <b>No</b>' ; 
                }
            }
            return result;    
    }

    public String respDailyTasks {
        get {
            String result = responseRating(this.record.Rating_applicant_s_ability_to_do_tasks__c);
            return result;
        }
    }

    public String respCommSkills{
        get {
            String result = responseRating(this.record.Communication_Documentation_Skills__c);
            return result;
        }
    }
    
    public String respClinicalSkills {
        get {
            // String result = responseRating(this.record.Clinical_Skills__c);
            String result = '';
            switch on this.record.Clinical_Skills__c{
                when 'Needing assistance'{
                    result += 'Highly skilled | Competent | <b>Needing assistance</b> | Not applicable' ;     
                }
                when 'Highly skilled'{
                    result += '<b>Highly skilled</b> | Competent | Needing assistance | Not applicable' ;     
                }
                when 'Competent'{
                    result += 'Highly skilled | <b>Competent</b> | Needing assistance | Not applicable' ;     
                }
                when 'Not applicable'{
                    result += 'Highly skilled | Competent | Needing assistance | <b>Not applicable</b>' ;     
                }
            }
            return result;
        }
    }

    public String respEmergencySits {
        get {
            String result = responseRating(this.record.Dealing_with_emergency_situation__c);
            return result;
        }
    }

    private String responseRating(String rating){
            String result = '';
            switch on rating{
                when '1'{
                    result += '<b>1</b> | 2 | 3 | 4 | 5' ;     
                }
                when '2'{
                    result += '1 | <b>2</b> | 3 | 4 | 5' ;
                }
                when '3'{
                    result += '1 | 2 | <b>3</b> | 4 | 5' ;
                }
                when '4'{
                    result += '1 | 2 | 3 | <b>4</b> | 5' ;
                }
                when '5'{
                    result += '1 | 2 | 3 | 4 | <b>5</b>' ;
                }
            }
            return result;
    }

}