.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Adhering_to_OHS_guidelines__c.field-meta.xml
<CustomField>
    <fullName>Adhering_to_OHS_guidelines__c</fullName>
    <inlineHelpText>Does “applicant” adhere to OHS guidelines (e.g. infection control, PPE, security, handwashing &amp; lifting)</inlineHelpText>
    <label>Adhering to OHS guidelines</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/AHPRA_based_investigations_or_disputes__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_based_investigations_or_disputes__c</fullName>
    <inlineHelpText>Has candidate been subject to any Facility or AHPRA based investigations, disputes or complaints?</inlineHelpText>
    <label>AHPRA based investigations or disputes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Applicant_can_work_unsupervised__c.field-meta.xml
<CustomField>
    <fullName>Applicant_can_work_unsupervised__c</fullName>
    <inlineHelpText>Would you say “applicant” performance is consistent &amp; are they able to work well unsupervised?</inlineHelpText>
    <label>Applicant can work unsupervised</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Clinical_Skills__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Skills__c</fullName>
    <inlineHelpText>How would you rate the clinical skills demonstrated by the candidate in this role?</inlineHelpText>
    <label>Clinical Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highly skilled</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Needing assistance</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Communication_Documentation_Skills__c.field-meta.xml
<CustomField>
    <fullName>Communication_Documentation_Skills__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” communication / documentation skills (if electronic notes are used, can you comment on their effectiveness)</inlineHelpText>
    <label>Communication / Documentation Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Dealing_with_emergency_situation__c.field-meta.xml
<CustomField>
    <fullName>Dealing_with_emergency_situation__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” ability to deal with emergency situations &amp; do you have confidence they are able to accurately assess, diagnose &amp; treat in these situations?</inlineHelpText>
    <label>Dealing with emergency situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Handling_medication_administration__c.field-meta.xml
<CustomField>
    <fullName>Handling_medication_administration__c</fullName>
    <inlineHelpText>Does “applicant” demonstrate due care &amp; attention to medication administration/ distribution? Any errors to your knowledge?</inlineHelpText>
    <label>Handling medication administration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Happy_to_provide_References__c.field-meta.xml
<CustomField>
    <fullName>Happy_to_provide_References__c</fullName>
    <inlineHelpText>Are you happy to provide a reference for your time working with the candidate?</inlineHelpText>
    <label>Happy to provide References?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Permission_to_disclose_reference_check__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_disclose_reference_check__c</fullName>
    <inlineHelpText>Do you give permission for us to disclose this reference check to candidate if requested?</inlineHelpText>
    <label>Permission to disclose reference check</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Rating_applicant_s_ability_to_do_tasks__c.field-meta.xml
<CustomField>
    <fullName>Rating_applicant_s_ability_to_do_tasks__c</fullName>
    <inlineHelpText>How would you rate “applicant’s” ability to carry out their daily duties (time management, ability to prioritise etc)</inlineHelpText>
    <label>Rating applicant&apos;s ability to do tasks</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/objects/b3o__Reference__c/fields/Rehire_applicant_further_comments__c.field-meta.xml
<CustomField>
    <fullName>Rehire_applicant_further_comments__c</fullName>
    <inlineHelpText>Would you rehire “applicant” &amp; do you have any further comments you’d like to make?</inlineHelpText>
    <label>Rehire applicant &amp; further comments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.vscode/allianceuat_compare/force-app/main/default/classes/ReferenceCheckExtension_test.cls
@isTest
private class ReferenceCheckExtension_test {
    public static Account acc = new Account();
    public static Contact cont = new Contact();
    public static b3o__Reference__c ref = new b3o__Reference__c();

    @isTest
    static void generateReferenceTest() {
        createData();
        PageReference pageRef = Page.ReferenceCheck;
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sController1 = new ApexPages.StandardController(ref);

        Test.startTest();
        ReferenceCheckExtension controller1 = new ReferenceCheckExtension(sController1);
        Test.stopTest();

        System.debug('controller1.firstNameApos ' + controller1.firstNameApos);
        System.debug('controller1.ratingDailyTasks ' + controller1.ratingDailyTasks);
        System.debug('controller1.ratingCommSkills ' + controller1.ratingCommSkills);
        System.debug('controller1.ratingClinicalSkills ' + controller1.ratingClinicalSkills);
        System.debug('controller1.ratingEmergencySits ' + controller1.ratingEmergencySits);
        System.debug('controller1.respProvideRefs ' + controller1.respProvideRefs);
        System.debug('controller1.respDiscloseRefs ' + controller1.respDiscloseRefs);
        System.debug('controller1.respAHPRAInvDisps ' + controller1.respAHPRAInvDisps);
        System.debug('controller1.respApplUnsupervised ' + controller1.respApplUnsupervised);
        System.debug('controller1.respDailyTasks ' + controller1.respDailyTasks);
        System.debug('controller1.respHandlingMeds ' + controller1.respHandlingMeds);
        System.debug('controller1.respOHSGuidelines ' + controller1.respOHSGuidelines);
        System.debug('controller1.respRehireAppl ' + controller1.respRehireAppl);
        System.debug('controller1.respDailyTasks ' + controller1.respDailyTasks);
        System.debug('controller1.respCommSkills ' + controller1.respCommSkills);
        System.debug('controller1.respClinicalSkills ' + controller1.respClinicalSkills);
        System.debug('controller1.respEmergencySits ' + controller1.respEmergencySits);

        String firstNameAposTest = 'First\'s';
        Boolean ratingDailyTasksTest = true;
        Boolean ratingCommSkillsTest = true;
        Boolean ratingClinicalSkillsTest = false;
        Boolean ratingEmergencySitsTest = false;
        String respProvideRefsTest = '<b>Yes</b> | No';
        String respDiscloseRefsTest = '<b>Yes</b> | No';
        String respAHPRAInvDispsest = '<b>Yes</b> | No';
        String respApplUnsupervisedTest = 'Yes | <b>No</b>';
        String respDailyTasksTest = '<b>1</b> | 2 | 3 | 4 | 5';
        String respHandlingMedsTest = '<b>Yes</b> | No';
        String respOHSGuidelinesTest = '<b>Yes</b> | No';
        String respRehireApplTest = '<b>Yes</b> | No';
        String respCommSkillsTest = '1 | 2 | <b>3</b> | 4 | 5';
        String respClinicalSkillsTest = 'Highly skilled | <b>Competent</b> | Needing assistance | Not applicable';
        String respEmergencySitsTest = '1 | 2 | 3 | <b>4</b> | 5';

        System.assertEquals(firstNameAposTest, controller1.firstNameApos, 'First Name');
        System.assertEquals(ratingDailyTasksTest, controller1.ratingDailyTasks, 'Daily Tasks');
        System.assertEquals(ratingCommSkillsTest, controller1.ratingCommSkills, 'Comm Skills');
        System.assertEquals(ratingClinicalSkillsTest, controller1.ratingClinicalSkills, 'Clinical Skills');
        System.assertEquals(ratingEmergencySitsTest, controller1.ratingEmergencySits, 'Emergency Situations'); 
        System.assertEquals(respProvideRefsTest, controller1.respProvideRefs, 'Provide Refs');
        System.assertEquals(respAHPRAInvDispsest, controller1.respAHPRAInvDisps, 'AHPRA Investigations');
        System.assertEquals(respApplUnsupervisedTest, controller1.respApplUnsupervised, 'Unsupervised');
        System.assertEquals(respDailyTasksTest, controller1.respDailyTasks, 'Daily Tasks');
        System.assertEquals(respHandlingMedsTest, controller1.respHandlingMeds, 'Handling Meds');
        System.assertEquals(respOHSGuidelinesTest, controller1.respOHSGuidelines, 'OHS Guidelines');
        System.assertEquals(respRehireApplTest, controller1.respRehireAppl, 'Rehire');
        System.assertEquals(respCommSkillsTest, controller1.respCommSkills, 'Comm Skills Response');
        System.assertEquals(respClinicalSkillsTest, controller1.respClinicalSkills, 'Clinical Skills Response');
        System.assertEquals(respEmergencySitsTest, controller1.respEmergencySits, 'Emergency Situations Response');

    }

    public static void createData(){
        acc = SIM_TestDataFactory.genTestAccount('accountName', 'Candidate Pool', true);
        cont = SIM_TestDataFactory.genTestContact('LastName', acc.Id, 'Candidate', false);
        cont.FirstName = 'First';
        cont.Email = '1218-SFDC-Support@1218global.com';
        cont.LastName = 'LastName';
        insert cont; 

        // clientAcc = SIM_TestDataFactory.genTestAccount('Client Account', 'Client', true);
        // clientCont = SIM_TestDataFactory.genTestContact('Client', clientAcc.Id, 'Client Contact', true);

        ref = new b3o__Reference__c(
            b3o__Contact__c = cont.id,
            Rating_applicant_s_ability_to_do_tasks__c = '1',
            Communication_Documentation_Skills__c = '3',
            Clinical_Skills__c = 'Competent',
            Dealing_with_emergency_situation__c = '4',
            Happy_to_provide_References__c = 'Yes',
            Permission_to_disclose_reference_check__c = 'Yes',
            AHPRA_based_investigations_or_disputes__c = 'Yes',
            Applicant_can_work_unsupervised__c = 'No',
            Handling_medication_administration__c = 'Yes',
            Adhering_to_OHS_guidelines__c = 'Yes',
            Rehire_applicant_further_comments__c = 'Yes'
        );
        insert ref;



    }
}